syntax = "proto3";

package pocketpet.world;

option go_package = "pocket-pet-remake/proto/world;worldpb";

import "proto/common/types.proto";

enum InteractType {
  INTERACT_TYPE_UNSPECIFIED = 0;
  INTERACT_TYPE_NPC = 1;
  INTERACT_TYPE_PORTAL = 2;
  INTERACT_TYPE_MONSTER = 3;
  INTERACT_TYPE_PICKUP = 4;
}

enum EncounterType {
  ENCOUNTER_TYPE_UNSPECIFIED = 0;
  ENCOUNTER_TYPE_WILD = 1;
  ENCOUNTER_TYPE_SCRIPT = 2;
}

message EnterWorldReq {}

message PlayerSnapshot {
  uint64 player_id = 1;
  string name = 2;
  uint32 level = 3;
  uint64 exp = 4;
  uint32 gold = 5;
  uint32 hp = 6;
  uint32 hp_max = 7;
  uint32 energy = 8;
  uint32 energy_max = 9;
  uint32 atk = 10;
  uint32 def = 11;
  uint32 spd = 12;
  uint32 mana = 13;
  uint32 hit_pct = 14;
  uint32 dodge_pct = 15;
  uint32 crit_rate_pct = 16;
  uint32 crit_dmg_pct = 17;
  uint32 physical_resist_pct = 18;
  uint32 skill_resist_pct = 19;
  uint32 confusion_resist_pct = 20;
  uint32 sleep_resist_pct = 21;
  uint32 paralysis_resist_pct = 22;
  uint32 seal_resist_pct = 23;
  uint32 curse_resist_pct = 24;
  uint32 crit_resist_pct = 25;
  uint32 crit_dmg_resist_pct = 26;
  uint32 character_resist_pct = 27;
  uint32 pet_resist_pct = 28;
  uint32 mercenary_resist_pct = 29;
  uint32 generic_shield_pct = 30;
  repeated uint32 skill_ids = 31;
}

message EnterWorldResp {
  pocketpet.common.PlayerBrief self = 1;
  PlayerSnapshot player = 2;
  uint32 scene_id = 3;
  pocketpet.common.Vec2i self_pos = 4;
  uint32 scene_version = 5;
  repeated pocketpet.common.EntityBrief nearby_entities = 6;
  repeated pocketpet.common.PetBrief lineup = 7;
  uint32 gold = 8;
}

message EntityEnterPush {
  uint32 scene_version = 1;
  pocketpet.common.EntityBrief entity = 2;
}

message EntityLeavePush {
  uint32 scene_version = 1;
  uint64 entity_id = 2;
}

message MoveIntentReq {
  uint32 op_id = 1;
  uint32 move_seq = 2;
  uint32 scene_id = 3;
  uint32 target_scene_id = 4;
  uint32 portal_id = 5;
}

message MoveIntentResp {
  bool accepted = 1;
  uint32 move_seq = 2;
  uint32 scene_id = 3;
  pocketpet.common.Vec2i corrected_pos = 4;
  string reason = 5;
}

message EntityMovePush {
  uint32 scene_version = 1;
  uint64 entity_id = 2;
  uint32 move_seq = 3;
  pocketpet.common.Vec2i from_pos = 4;
  pocketpet.common.Vec2i to_pos = 5;
  uint32 speed = 6;
}

message WorldResyncPush {
  uint32 scene_id = 1;
  pocketpet.common.Vec2i self_pos = 2;
  uint32 scene_version = 3;
  repeated pocketpet.common.EntityBrief nearby_entities = 4;
}

message InteractReq {
  uint32 op_id = 1;
  uint64 target_entity_id = 2;
  InteractType interact_type = 3;
}

message InteractResp {
  bool accepted = 1;
  string reason = 2;
}

message EncounterPush {
  uint64 battle_id = 1;
  EncounterType encounter_type = 2;
  uint64 monster_group_id = 3;
}
