syntax = "proto3";

package pocketpet.common;

option go_package = "pocket-pet-remake/proto/common;commonpb";

message Vec2i {
  int32 x = 1;
  int32 y = 2;
}

message PlayerBrief {
  uint64 player_id = 1;
  string name = 2;
  uint32 level = 3;
}

message EntityBrief {
  uint64 entity_id = 1;
  uint32 entity_type = 2;
  Vec2i pos = 3;
  uint32 dir = 4;
  uint32 speed = 5;
  string name = 6;
  uint64 player_id = 7;
  uint32 level = 8;
  uint64 exp = 9;
  uint32 hp = 10;
  uint32 hp_max = 11;
  uint32 vigor = 12;
  uint32 vigor_max = 13;
  uint32 spirit = 14;
  uint32 spirit_max = 15;
  string skin_id = 16;
  PetBrief following_pet = 17;
}

message PetBrief {
  uint64 pet_uid = 1;
  uint32 pet_id = 2;
  uint32 level = 3;
  uint32 hp = 4;
  uint32 hp_max = 5;
  string name = 6;
  uint64 exp = 7;
  uint32 spirit = 8;
  uint32 spirit_max = 9;
  string skin_id = 10;
}

message ItemBrief {
  uint64 item_uid = 1;
  uint32 item_id = 2;
  uint32 count = 3;
}

message Reward {
  uint32 gold = 1;
  uint32 exp = 2;
  repeated ItemBrief items = 3;
}
