CREATE TABLE `account` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_name` VARCHAR(64) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `last_login_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_account_name` (`account_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `player` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `level` INT UNSIGNED NOT NULL DEFAULT 1,
  `exp` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `gold` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `scene_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `pos_x` INT NOT NULL DEFAULT 0,
  `pos_y` INT NOT NULL DEFAULT 0,
  `hp` INT UNSIGNED NOT NULL DEFAULT 100,
  `hp_max` INT UNSIGNED NOT NULL DEFAULT 100,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_player_name` (`name`),
  KEY `idx_player_account_id` (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `player_pet` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `player_id` BIGINT UNSIGNED NOT NULL,
  `pet_id` INT UNSIGNED NOT NULL,
  `level` INT UNSIGNED NOT NULL DEFAULT 1,
  `exp` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `quality` INT UNSIGNED NOT NULL DEFAULT 1,
  `hp` INT UNSIGNED NOT NULL DEFAULT 1,
  `hp_max` INT UNSIGNED NOT NULL DEFAULT 1,
  `atk` INT UNSIGNED NOT NULL DEFAULT 1,
  `def` INT UNSIGNED NOT NULL DEFAULT 1,
  `spd` INT UNSIGNED NOT NULL DEFAULT 1,
  `skill_ids` JSON NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_player_pet_player_id` (`player_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `player_item` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `player_id` BIGINT UNSIGNED NOT NULL,
  `item_id` INT UNSIGNED NOT NULL,
  `count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_player_item` (`player_id`, `item_id`),
  KEY `idx_player_item_player_id` (`player_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `player_lineup` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `player_id` BIGINT UNSIGNED NOT NULL,
  `slot_index` INT UNSIGNED NOT NULL,
  `pet_uid` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_player_lineup_slot` (`player_id`, `slot_index`),
  UNIQUE KEY `uk_player_lineup_pet` (`player_id`, `pet_uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `battle_record` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `battle_id` BIGINT UNSIGNED NOT NULL,
  `player_id` BIGINT UNSIGNED NOT NULL,
  `battle_type` INT UNSIGNED NOT NULL,
  `result` TINYINT UNSIGNED NOT NULL,
  `reward_gold` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `reward_exp` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `captured_pet_uid` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `payload_json` JSON NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_battle_record_battle_player` (`battle_id`, `player_id`),
  KEY `idx_battle_record_player_id` (`player_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
