INSERT INTO quest_template (
  quest_id,
  quest_type,
  name,
  title,
  description,
  chapter,
  sort_order,
  accept_mode,
  submit_mode,
  can_abandon,
  is_repeatable,
  auto_track,
  start_npc_id,
  submit_npc_id,
  min_player_level,
  visible_conditions,
  unlock_conditions,
  accept_conditions,
  pre_quest_ids,
  objectives_json,
  rewards_json,
  tags_json,
  time_window_json,
  version,
  status
) VALUES
(
  1001,
  'MAIN',
  'main_enter_east_road',
  '初入闪光镇',
  '前往闪光镇东路，熟悉周围环境。',
  1,
  10,
  'AUTO',
  'AUTO',
  FALSE,
  FALSE,
  TRUE,
  0,
  0,
  1,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[
    {
      "objective_id": 1,
      "event_type": "ENTER_SCENE",
      "description": "进入闪光镇东路",
      "target": 1,
      "target_selector": { "scene_id": 2 },
      "guide": { "scene_id": 2, "npc_id": 0, "text": "前往闪光镇东路" }
    }
  ]'::jsonb,
  '[
    { "type": "gold", "value": 100 }
  ]'::jsonb,
  '["main","newbie"]'::jsonb,
  '{}'::jsonb,
  1,
  1
),
(
  1002,
  'MAIN',
  'main_report_market_manager',
  '向市场管理员报到',
  '找到市场理萌并和她交谈。',
  1,
  20,
  'NPC',
  'NPC',
  FALSE,
  FALSE,
  TRUE,
  93001,
  93001,
  1,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[1001]'::jsonb,
  '[
    {
      "objective_id": 1,
      "event_type": "TALK_TO_NPC",
      "description": "与市场理萌交谈",
      "target": 1,
      "target_selector": { "npc_id": 93001 },
      "guide": { "scene_id": 3, "npc_id": 93001, "text": "去商业区找市场理萌" }
    }
  ]'::jsonb,
  '[
    { "type": "gold", "value": 150 },
    { "type": "item", "item_id": 2001, "count": 2, "value": 0 }
  ]'::jsonb,
  '["main","npc"]'::jsonb,
  '{}'::jsonb,
  1,
  1
),
(
  1003,
  'MAIN',
  'main_first_battle',
  '完成第一次对战',
  '挑战附近的教学 NPC 并赢得胜利。',
  1,
  30,
  'AUTO',
  'AUTO',
  FALSE,
  FALSE,
  TRUE,
  0,
  0,
  1,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[1002]'::jsonb,
  '[
    {
      "objective_id": 1,
      "event_type": "WIN_BATTLE",
      "description": "完成 1 场战斗",
      "target": 1,
      "target_selector": { "battle_type": "PVE" },
      "guide": { "scene_id": 6, "npc_id": 90006, "text": "去训练区完成第一次战斗" }
    }
  ]'::jsonb,
  '[
    { "type": "gold", "value": 200 },
    { "type": "feature_unlock", "value": 1 }
  ]'::jsonb,
  '["main","battle"]'::jsonb,
  '{}'::jsonb,
  1,
  1
)
ON CONFLICT (quest_id) DO UPDATE SET
  quest_type = EXCLUDED.quest_type,
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  chapter = EXCLUDED.chapter,
  sort_order = EXCLUDED.sort_order,
  accept_mode = EXCLUDED.accept_mode,
  submit_mode = EXCLUDED.submit_mode,
  can_abandon = EXCLUDED.can_abandon,
  is_repeatable = EXCLUDED.is_repeatable,
  auto_track = EXCLUDED.auto_track,
  start_npc_id = EXCLUDED.start_npc_id,
  submit_npc_id = EXCLUDED.submit_npc_id,
  min_player_level = EXCLUDED.min_player_level,
  visible_conditions = EXCLUDED.visible_conditions,
  unlock_conditions = EXCLUDED.unlock_conditions,
  accept_conditions = EXCLUDED.accept_conditions,
  pre_quest_ids = EXCLUDED.pre_quest_ids,
  objectives_json = EXCLUDED.objectives_json,
  rewards_json = EXCLUDED.rewards_json,
  tags_json = EXCLUDED.tags_json,
  time_window_json = EXCLUDED.time_window_json,
  version = EXCLUDED.version,
  status = EXCLUDED.status;
