-- 018_seed_bag_expand_items.sql
--
-- 本迁移为“背包扩容券 / 仓库扩容券”的正式模板配置补种子数据。
-- 设计目标：
-- 1. 让 `5021/5022 USE_ITEM` 的第一批正式功能道具有数据库事实来源。
-- 2. 保持配置幂等，用户在测试库或重复执行时不会插入重复模板。
-- 3. 把“模板主表字段”和“功能扩展字段”同时落库，避免运行时再写硬编码常量。

-- 新增背包扩容券模板。
-- 当前约定 item_id = 3001，使用后给随身背包增加 5 个格子。
INSERT INTO item_definition (
  item_id,
  item_code,
  item_name,
  item_type,
  item_sub_type,
  quality,
  rarity,
  icon,
  "desc",
  max_stack,
  occupy_slots,
  auto_merge,
  sort_weight,
  usable,
  use_scope,
  target_type,
  required_level,
  required_scene_id,
  bind_type,
  can_sell,
  can_drop,
  can_store,
  can_trade,
  expire_at_rule,
  effect_type,
  effect_value,
  effect_params_json,
  buy_price_copper,
  sell_price_copper,
  recycle_price_copper,
  price_type,
  is_enabled
) VALUES (
  3001,
  'bag_expand_ticket_small',
  '背包扩容券',
  'functional',
  'expand',
  2,
  2,
  '',
  '使用后永久增加 5 个背包格子。',
  99,
  1,
  TRUE,
  200,
  TRUE,
  'world',
  'self',
  1,
  0,
  'pickup_bind',
  FALSE,
  FALSE,
  TRUE,
  FALSE,
  '',
  'bag_expand',
  5,
  '{"expand_target":"bag","expand_slots":5}'::jsonb,
  0,
  0,
  0,
  'base_coin',
  TRUE
)
ON CONFLICT (item_id) DO UPDATE
SET item_code = EXCLUDED.item_code,
    item_name = EXCLUDED.item_name,
    item_type = EXCLUDED.item_type,
    item_sub_type = EXCLUDED.item_sub_type,
    quality = EXCLUDED.quality,
    rarity = EXCLUDED.rarity,
    icon = EXCLUDED.icon,
    "desc" = EXCLUDED."desc",
    max_stack = EXCLUDED.max_stack,
    occupy_slots = EXCLUDED.occupy_slots,
    auto_merge = EXCLUDED.auto_merge,
    sort_weight = EXCLUDED.sort_weight,
    usable = EXCLUDED.usable,
    use_scope = EXCLUDED.use_scope,
    target_type = EXCLUDED.target_type,
    required_level = EXCLUDED.required_level,
    required_scene_id = EXCLUDED.required_scene_id,
    bind_type = EXCLUDED.bind_type,
    can_sell = EXCLUDED.can_sell,
    can_drop = EXCLUDED.can_drop,
    can_store = EXCLUDED.can_store,
    can_trade = EXCLUDED.can_trade,
    expire_at_rule = EXCLUDED.expire_at_rule,
    effect_type = EXCLUDED.effect_type,
    effect_value = EXCLUDED.effect_value,
    effect_params_json = EXCLUDED.effect_params_json,
    buy_price_copper = EXCLUDED.buy_price_copper,
    sell_price_copper = EXCLUDED.sell_price_copper,
    recycle_price_copper = EXCLUDED.recycle_price_copper,
    price_type = EXCLUDED.price_type,
    is_enabled = EXCLUDED.is_enabled,
    updated_at = CURRENT_TIMESTAMP;

-- 新增仓库扩容券模板。
-- 当前约定 item_id = 3002，使用后给个人仓库增加 5 个格子。
INSERT INTO item_definition (
  item_id,
  item_code,
  item_name,
  item_type,
  item_sub_type,
  quality,
  rarity,
  icon,
  "desc",
  max_stack,
  occupy_slots,
  auto_merge,
  sort_weight,
  usable,
  use_scope,
  target_type,
  required_level,
  required_scene_id,
  bind_type,
  can_sell,
  can_drop,
  can_store,
  can_trade,
  expire_at_rule,
  effect_type,
  effect_value,
  effect_params_json,
  buy_price_copper,
  sell_price_copper,
  recycle_price_copper,
  price_type,
  is_enabled
) VALUES (
  3002,
  'warehouse_expand_ticket_small',
  '仓库扩容券',
  'functional',
  'expand',
  2,
  2,
  '',
  '使用后永久增加 5 个仓库格子。',
  99,
  1,
  TRUE,
  201,
  TRUE,
  'world',
  'self',
  1,
  0,
  'pickup_bind',
  FALSE,
  FALSE,
  TRUE,
  FALSE,
  '',
  'warehouse_expand',
  5,
  '{"expand_target":"warehouse","expand_slots":5}'::jsonb,
  0,
  0,
  0,
  'base_coin',
  TRUE
)
ON CONFLICT (item_id) DO UPDATE
SET item_code = EXCLUDED.item_code,
    item_name = EXCLUDED.item_name,
    item_type = EXCLUDED.item_type,
    item_sub_type = EXCLUDED.item_sub_type,
    quality = EXCLUDED.quality,
    rarity = EXCLUDED.rarity,
    icon = EXCLUDED.icon,
    "desc" = EXCLUDED."desc",
    max_stack = EXCLUDED.max_stack,
    occupy_slots = EXCLUDED.occupy_slots,
    auto_merge = EXCLUDED.auto_merge,
    sort_weight = EXCLUDED.sort_weight,
    usable = EXCLUDED.usable,
    use_scope = EXCLUDED.use_scope,
    target_type = EXCLUDED.target_type,
    required_level = EXCLUDED.required_level,
    required_scene_id = EXCLUDED.required_scene_id,
    bind_type = EXCLUDED.bind_type,
    can_sell = EXCLUDED.can_sell,
    can_drop = EXCLUDED.can_drop,
    can_store = EXCLUDED.can_store,
    can_trade = EXCLUDED.can_trade,
    expire_at_rule = EXCLUDED.expire_at_rule,
    effect_type = EXCLUDED.effect_type,
    effect_value = EXCLUDED.effect_value,
    effect_params_json = EXCLUDED.effect_params_json,
    buy_price_copper = EXCLUDED.buy_price_copper,
    sell_price_copper = EXCLUDED.sell_price_copper,
    recycle_price_copper = EXCLUDED.recycle_price_copper,
    price_type = EXCLUDED.price_type,
    is_enabled = EXCLUDED.is_enabled,
    updated_at = CURRENT_TIMESTAMP;

-- 为两种扩容券补齐功能扩展表。
-- 运行时扩容逻辑会优先从 `item_functional_extra` 读取扩容目标与扩容格数。
INSERT INTO item_functional_extra (
  item_id,
  function_type,
  expand_target,
  expand_slots,
  target_rule_json
) VALUES
  (3001, 'expand_container', 'bag', 5, '{}'::jsonb),
  (3002, 'expand_container', 'warehouse', 5, '{}'::jsonb)
ON CONFLICT (item_id) DO UPDATE
SET function_type = EXCLUDED.function_type,
    expand_target = EXCLUDED.expand_target,
    expand_slots = EXCLUDED.expand_slots,
    target_rule_json = EXCLUDED.target_rule_json,
    updated_at = CURRENT_TIMESTAMP;
