-- 019_seed_pet_heal_items.sql
--
-- 本迁移补充第一批正式可主动使用的宠物治疗药剂模板。
-- 目标是让 `5021/5022 USE_ITEM` 在扩容券之外，也能从数据库里读取真实可用的宠物恢复配置。

INSERT INTO item_definition (
  item_id,
  item_code,
  item_name,
  item_type,
  item_sub_type,
  quality,
  rarity,
  icon,
  "desc",
  max_stack,
  occupy_slots,
  auto_merge,
  sort_weight,
  usable,
  use_scope,
  target_type,
  required_level,
  required_scene_id,
  bind_type,
  can_sell,
  can_drop,
  can_store,
  can_trade,
  expire_at_rule,
  effect_type,
  effect_value,
  effect_params_json,
  buy_price_copper,
  sell_price_copper,
  recycle_price_copper,
  price_type,
  is_enabled
) VALUES (
  3003,
  'pet_hp_potion_small',
  '宠物治疗药剂',
  'consumable',
  'pet_restore',
  1,
  1,
  'res://asset/icons/items/pet_hp_potion_small.png',
  '恢复己方单只宠物 10 点生命值。',
  99,
  1,
  TRUE,
  220,
  TRUE,
  'world',
  'pet_single',
  1,
  0,
  'none',
  TRUE,
  TRUE,
  TRUE,
  FALSE,
  '',
  'pet_hp_restore',
  10,
  '{"restore_type":"flat","target":"pet_single"}'::jsonb,
  500,
  100,
  0,
  'base_coin',
  TRUE
)
ON CONFLICT (item_id) DO UPDATE SET
  item_code = EXCLUDED.item_code,
  item_name = EXCLUDED.item_name,
  item_type = EXCLUDED.item_type,
  item_sub_type = EXCLUDED.item_sub_type,
  quality = EXCLUDED.quality,
  rarity = EXCLUDED.rarity,
  icon = EXCLUDED.icon,
  "desc" = EXCLUDED."desc",
  max_stack = EXCLUDED.max_stack,
  occupy_slots = EXCLUDED.occupy_slots,
  auto_merge = EXCLUDED.auto_merge,
  sort_weight = EXCLUDED.sort_weight,
  usable = EXCLUDED.usable,
  use_scope = EXCLUDED.use_scope,
  target_type = EXCLUDED.target_type,
  required_level = EXCLUDED.required_level,
  required_scene_id = EXCLUDED.required_scene_id,
  bind_type = EXCLUDED.bind_type,
  can_sell = EXCLUDED.can_sell,
  can_drop = EXCLUDED.can_drop,
  can_store = EXCLUDED.can_store,
  can_trade = EXCLUDED.can_trade,
  expire_at_rule = EXCLUDED.expire_at_rule,
  effect_type = EXCLUDED.effect_type,
  effect_value = EXCLUDED.effect_value,
  effect_params_json = EXCLUDED.effect_params_json,
  buy_price_copper = EXCLUDED.buy_price_copper,
  sell_price_copper = EXCLUDED.sell_price_copper,
  recycle_price_copper = EXCLUDED.recycle_price_copper,
  price_type = EXCLUDED.price_type,
  is_enabled = EXCLUDED.is_enabled,
  updated_at = CURRENT_TIMESTAMP;
