-- 020_seed_battle_drop_items.sql
--
-- 本迁移补充当前 PVE MVP 会真实掉落到背包的第一批正式物品模板。
-- 目标：
-- 1. 让战斗掉落进入 `bag` 时拥有数据库事实来源，而不是依赖运行时假数据。
-- 2. 保持模板幂等，重复执行时只更新正式字段，不重复插入。
-- 3. 先覆盖当前战斗模块内已经使用到的四种最小掉落物品，后续再继续数据化掉落表。

INSERT INTO item_definition (
  item_id,
  item_code,
  item_name,
  item_type,
  item_sub_type,
  quality,
  rarity,
  icon,
  "desc",
  max_stack,
  occupy_slots,
  auto_merge,
  sort_weight,
  usable,
  use_scope,
  target_type,
  required_level,
  required_scene_id,
  bind_type,
  can_sell,
  can_drop,
  can_store,
  can_trade,
  expire_at_rule,
  effect_type,
  effect_value,
  effect_params_json,
  buy_price_copper,
  sell_price_copper,
  recycle_price_copper,
  price_type,
  is_enabled
) VALUES
  (
    3101,
    'battle_drop_wild_fur',
    '野性毛皮',
    'material',
    'battle_drop',
    1,
    1,
    '',
    '常见野外怪物掉落的基础材料。',
    99,
    1,
    TRUE,
    120,
    FALSE,
    'world',
    'none',
    1,
    0,
    'none',
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    '',
    '',
    0,
    '{}'::jsonb,
    0,
    80,
    0,
    'base_coin',
    TRUE
  ),
  (
    3102,
    'battle_drop_claw_fragment',
    '锋爪碎片',
    'material',
    'battle_drop',
    1,
    1,
    '',
    '较强野兽掉落的爪类碎片，可用于后续兑换或打造。',
    99,
    1,
    TRUE,
    121,
    FALSE,
    'world',
    'none',
    1,
    0,
    'none',
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    '',
    '',
    0,
    '{}'::jsonb,
    0,
    120,
    0,
    'base_coin',
    TRUE
  ),
  (
    3103,
    'battle_drop_training_badge',
    '训练徽记',
    'token',
    'battle_drop',
    2,
    2,
    '',
    '更高等级敌人掉落的训练凭证。',
    99,
    1,
    TRUE,
    122,
    FALSE,
    'world',
    'none',
    1,
    0,
    'none',
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    '',
    '',
    0,
    '{}'::jsonb,
    0,
    200,
    0,
    'base_coin',
    TRUE
  ),
  (
    3104,
    'battle_drop_heal_leaf',
    '治愈草叶',
    'material',
    'battle_drop',
    1,
    1,
    '',
    '低级怪物常见掉落的草叶材料。',
    99,
    1,
    TRUE,
    123,
    FALSE,
    'world',
    'none',
    1,
    0,
    'none',
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    '',
    '',
    0,
    '{}'::jsonb,
    0,
    60,
    0,
    'base_coin',
    TRUE
  )
ON CONFLICT (item_id) DO UPDATE SET
  item_code = EXCLUDED.item_code,
  item_name = EXCLUDED.item_name,
  item_type = EXCLUDED.item_type,
  item_sub_type = EXCLUDED.item_sub_type,
  quality = EXCLUDED.quality,
  rarity = EXCLUDED.rarity,
  icon = EXCLUDED.icon,
  "desc" = EXCLUDED."desc",
  max_stack = EXCLUDED.max_stack,
  occupy_slots = EXCLUDED.occupy_slots,
  auto_merge = EXCLUDED.auto_merge,
  sort_weight = EXCLUDED.sort_weight,
  usable = EXCLUDED.usable,
  use_scope = EXCLUDED.use_scope,
  target_type = EXCLUDED.target_type,
  required_level = EXCLUDED.required_level,
  required_scene_id = EXCLUDED.required_scene_id,
  bind_type = EXCLUDED.bind_type,
  can_sell = EXCLUDED.can_sell,
  can_drop = EXCLUDED.can_drop,
  can_store = EXCLUDED.can_store,
  can_trade = EXCLUDED.can_trade,
  expire_at_rule = EXCLUDED.expire_at_rule,
  effect_type = EXCLUDED.effect_type,
  effect_value = EXCLUDED.effect_value,
  effect_params_json = EXCLUDED.effect_params_json,
  buy_price_copper = EXCLUDED.buy_price_copper,
  sell_price_copper = EXCLUDED.sell_price_copper,
  recycle_price_copper = EXCLUDED.recycle_price_copper,
  price_type = EXCLUDED.price_type,
  is_enabled = EXCLUDED.is_enabled,
  updated_at = CURRENT_TIMESTAMP;
