-- 021_seed_reward_box_items.sql
--
-- 本迁移补充第一批礼包类道具模板。
-- 当前先落地一个最小的新手补给礼包，供 `5021/5022` 的礼包开启链路正式消费。

INSERT INTO item_definition (
  item_id,
  item_code,
  item_name,
  item_type,
  item_sub_type,
  quality,
  rarity,
  icon,
  "desc",
  max_stack,
  occupy_slots,
  auto_merge,
  sort_weight,
  usable,
  use_scope,
  target_type,
  required_level,
  required_scene_id,
  bind_type,
  can_sell,
  can_drop,
  can_store,
  can_trade,
  expire_at_rule,
  effect_type,
  effect_value,
  effect_params_json,
  buy_price_copper,
  sell_price_copper,
  recycle_price_copper,
  price_type,
  is_enabled
) VALUES (
  3004,
  'starter_reward_box',
  '新手补给礼包',
  'box',
  'reward_box',
  2,
  2,
  '',
  '开启后获得金币与基础新手道具。',
  99,
  1,
  TRUE,
  230,
  TRUE,
  'world',
  'self',
  1,
  0,
  'pickup_bind',
  FALSE,
  FALSE,
  TRUE,
  FALSE,
  '',
  'reward_box',
  0,
  '{"rewards":[{"type":"gold","value":2},{"type":"item","item_id":2001,"item_name":"新手精灵球","count":1}]}'::jsonb,
  0,
  0,
  0,
  'base_coin',
  TRUE
)
ON CONFLICT (item_id) DO UPDATE SET
  item_code = EXCLUDED.item_code,
  item_name = EXCLUDED.item_name,
  item_type = EXCLUDED.item_type,
  item_sub_type = EXCLUDED.item_sub_type,
  quality = EXCLUDED.quality,
  rarity = EXCLUDED.rarity,
  icon = EXCLUDED.icon,
  "desc" = EXCLUDED."desc",
  max_stack = EXCLUDED.max_stack,
  occupy_slots = EXCLUDED.occupy_slots,
  auto_merge = EXCLUDED.auto_merge,
  sort_weight = EXCLUDED.sort_weight,
  usable = EXCLUDED.usable,
  use_scope = EXCLUDED.use_scope,
  target_type = EXCLUDED.target_type,
  required_level = EXCLUDED.required_level,
  required_scene_id = EXCLUDED.required_scene_id,
  bind_type = EXCLUDED.bind_type,
  can_sell = EXCLUDED.can_sell,
  can_drop = EXCLUDED.can_drop,
  can_store = EXCLUDED.can_store,
  can_trade = EXCLUDED.can_trade,
  expire_at_rule = EXCLUDED.expire_at_rule,
  effect_type = EXCLUDED.effect_type,
  effect_value = EXCLUDED.effect_value,
  effect_params_json = EXCLUDED.effect_params_json,
  buy_price_copper = EXCLUDED.buy_price_copper,
  sell_price_copper = EXCLUDED.sell_price_copper,
  recycle_price_copper = EXCLUDED.recycle_price_copper,
  price_type = EXCLUDED.price_type,
  is_enabled = EXCLUDED.is_enabled,
  updated_at = CURRENT_TIMESTAMP;
