-- 023_skill_definition.sql
-- 系统技能模板主表：战斗结算、宠物模板、玩家技能与怪物技能统一引用 skill_id。

CREATE TABLE IF NOT EXISTS skill_definition (
  skill_id INTEGER PRIMARY KEY,
  skill_code VARCHAR(64) NOT NULL DEFAULT '',
  skill_name VARCHAR(64) NOT NULL DEFAULT '',
  skill_category VARCHAR(32) NOT NULL DEFAULT 'common',
  skill_type VARCHAR(32) NOT NULL DEFAULT 'attack',
  description TEXT NOT NULL DEFAULT '',
  acquire_method VARCHAR(128) NOT NULL DEFAULT '',
  target_type VARCHAR(32) NOT NULL DEFAULT 'enemy_single',
  target_count INTEGER NOT NULL DEFAULT 1,
  preferred_target_hp VARCHAR(32) NOT NULL DEFAULT '',
  animation_key VARCHAR(32) NOT NULL DEFAULT 'slash',
  cast_color VARCHAR(16) NOT NULL DEFAULT '#EBEBF5',
  impact_color VARCHAR(16) NOT NULL DEFAULT '#FFF2F2',
  projectile BOOLEAN NOT NULL DEFAULT FALSE,
  is_skill_attack BOOLEAN NOT NULL DEFAULT FALSE,
  is_basic_attack BOOLEAN NOT NULL DEFAULT FALSE,
  energy_cost INTEGER NOT NULL DEFAULT 0,
  allow_crit BOOLEAN NOT NULL DEFAULT TRUE,
  ignore_defense BOOLEAN NOT NULL DEFAULT FALSE,
  attack_pct INTEGER NOT NULL DEFAULT 100,
  mana_pct INTEGER NOT NULL DEFAULT 0,
  defense_pct INTEGER NOT NULL DEFAULT 0,
  speed_pct INTEGER NOT NULL DEFAULT 0,
  target_current_hp_pct INTEGER NOT NULL DEFAULT 0,
  fixed_damage INTEGER NOT NULL DEFAULT 0,
  heal_pct INTEGER NOT NULL DEFAULT 0,
  fixed_heal INTEGER NOT NULL DEFAULT 0,
  armor_break_pct INTEGER NOT NULL DEFAULT 0,
  vulnerability_pct INTEGER NOT NULL DEFAULT 0,
  bleed_chance_pct INTEGER NOT NULL DEFAULT 0,
  bleed_rounds INTEGER NOT NULL DEFAULT 0,
  bleed_damage INTEGER NOT NULL DEFAULT 0,
  seal_chance_pct INTEGER NOT NULL DEFAULT 0,
  seal_rounds INTEGER NOT NULL DEFAULT 0,
  vulnerability_chance_pct INTEGER NOT NULL DEFAULT 0,
  vulnerability_rounds INTEGER NOT NULL DEFAULT 0,
  vulnerability_apply_pct INTEGER NOT NULL DEFAULT 0,
  armor_break_chance_pct INTEGER NOT NULL DEFAULT 0,
  armor_break_rounds INTEGER NOT NULL DEFAULT 0,
  slow_chance_pct INTEGER NOT NULL DEFAULT 0,
  slow_rounds INTEGER NOT NULL DEFAULT 0,
  slow_multiplier_pct INTEGER NOT NULL DEFAULT 0,
  crit_boost_rounds INTEGER NOT NULL DEFAULT 0,
  crit_boost_pct INTEGER NOT NULL DEFAULT 0,
  curse_chance_pct INTEGER NOT NULL DEFAULT 0,
  curse_rounds INTEGER NOT NULL DEFAULT 0,
  curse_damage INTEGER NOT NULL DEFAULT 0,
  curse_mana_pct INTEGER NOT NULL DEFAULT 0,
  control_chance_pct INTEGER NOT NULL DEFAULT 0,
  control_rounds INTEGER NOT NULL DEFAULT 0,
  control_status_id INTEGER NOT NULL DEFAULT 0,
  sort_weight INTEGER NOT NULL DEFAULT 0,
  status INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_skill_definition_code
  ON skill_definition (skill_code)
  WHERE skill_code <> '';

CREATE TRIGGER set_skill_definition_updated_at
BEFORE UPDATE ON skill_definition
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 从现有 battle/skill.go skillCatalog 迁移初始模板。
INSERT INTO skill_definition (
  skill_id, skill_code, skill_name, skill_category, skill_type, description, acquire_method,
  target_type, target_count, preferred_target_hp,
  animation_key, cast_color, impact_color, projectile,
  is_skill_attack, is_basic_attack, energy_cost, allow_crit, ignore_defense,
  attack_pct, mana_pct, defense_pct, speed_pct, target_current_hp_pct, fixed_damage, heal_pct, fixed_heal,
  armor_break_pct, vulnerability_pct,
  bleed_chance_pct, bleed_rounds, bleed_damage,
  seal_chance_pct, seal_rounds,
  vulnerability_chance_pct, vulnerability_rounds, vulnerability_apply_pct,
  armor_break_chance_pct, armor_break_rounds,
  slow_chance_pct, slow_rounds, slow_multiplier_pct,
  crit_boost_rounds, crit_boost_pct,
  curse_chance_pct, curse_rounds, curse_damage, curse_mana_pct,
  control_chance_pct, control_rounds, control_status_id,
  sort_weight, status
) VALUES
  (
    1101, 'character_slash', '裂空斩', 'character', 'attack', '人物专属单体高伤技能', '角色默认技能',
    'enemy_single', 1, '',
    'slash', '#8FD6FF', '#BDE9FF', TRUE,
    TRUE, FALSE, 16, TRUE, FALSE,
    135, 55, 0, 35, 0, 0, 0, 0,
    0, 0,
    45, 2, 3,
    0, 0,
    0, 0, 0,
    100, 2,
    0, 0, 0,
    0, 0,
    0, 0, 0, 0,
    0, 0, 0,
    10, 1
  ),
  (
    1001, 'basic_attack', '普通攻击', 'common', 'attack', '全局默认普攻', '系统内置',
    'enemy_single', 1, '',
    'slash', '#EBEBF5', '#FFF2F2', FALSE,
    FALSE, TRUE, 0, TRUE, FALSE,
    100, 35, 0, 35, 0, 0, 0, 0,
    0, 0,
    0, 0, 0,
    0, 0,
    0, 0, 0,
    0, 0,
    0, 0, 0,
    0, 0,
    0, 0, 0, 0,
    0, 0, 0,
    1, 1
  ),
  (
    1002, 'pet_spark_burst', '火花冲击', 'pet', 'attack', '火系群体冲击', '宠物模板自带',
    'enemy_all', 0, '',
    'burst', '#FFAA5C', '#FFD46B', TRUE,
    TRUE, FALSE, 18, TRUE, FALSE,
    120, 85, 0, 55, 0, 0, 0, 0,
    0, 0,
    70, 2, 4,
    0, 0,
    100, 2, 12,
    0, 0,
    0, 0, 0,
    0, 0,
    0, 0, 0, 0,
    35, 1, 11,
    20, 1
  ),
  (
    1003, 'pet_vital_heal', '活力治愈', 'pet', 'heal', '单体治疗并附加暴击增益', '宠物模板自带',
    'ally_single', 1, 'lowest',
    'heal', '#73F5A3', '#B7FFD0', FALSE,
    TRUE, FALSE, 14, FALSE, FALSE,
    0, 0, 0, 0, 0, 0, 22, 0,
    0, 0,
    0, 0, 0,
    0, 0,
    0, 0, 0,
    0, 0,
    0, 0, 0,
    2, 20,
    0, 0, 0, 0,
    0, 0, 0,
    30, 1
  ),
  (
    1004, 'pet_arc_volley', '弧光连射', 'pet', 'attack', '多目标连射并附带控制概率', '宠物模板自带',
    'enemy_multi', 2, '',
    'volley', '#C6D1FF', '#ECECFF', TRUE,
    TRUE, FALSE, 16, TRUE, FALSE,
    105, 40, 0, 25, 0, 0, 0, 0,
    0, 0,
    40, 2, 2,
    0, 0,
    0, 0, 0,
    0, 0,
    0, 0, 0,
    0, 0,
    0, 0, 0, 0,
    20, 1, 12,
    40, 1
  ),
  (
    90001, 'monster_wild_charge', '野性撞击', 'monster', 'attack', '怪物默认单体攻击', '怪物模板',
    'enemy_single', 1, '',
    'slash', '#FFB88F', '#FFDDD1', FALSE,
    FALSE, FALSE, 0, TRUE, FALSE,
    95, 20, 0, 0, 0, 2, 0, 0,
    0, 0,
    0, 0, 0,
    0, 0,
    0, 0, 0,
    0, 0,
    0, 0, 0,
    0, 0,
    40, 2, 3, 0,
    0, 0, 0,
    100, 1
  ),
  (
    90002, 'monster_claw_strike', '利爪突袭', 'monster', 'attack', '怪物高速单体突袭', '怪物模板',
    'enemy_single', 1, '',
    'volley', '#FF9E85', '#FFC7BA', TRUE,
    FALSE, FALSE, 12, TRUE, FALSE,
    110, 30, 0, 20, 0, 0, 0, 0,
    0, 0,
    50, 2, 3,
    0, 0,
    0, 0, 0,
    0, 0,
    100, 2, 70,
    0, 0,
    0, 0, 0, 0,
    30, 1, 12,
    110, 1
  ),
  (
    90003, 'monster_wild_regen', '野性回春', 'monster', 'heal', '怪物治疗最低生命单位', '怪物模板',
    'ally_single', 1, 'lowest',
    'heal', '#84F8B3', '#C8FFE0', FALSE,
    TRUE, FALSE, 10, FALSE, FALSE,
    0, 0, 0, 0, 0, 0, 18, 0,
    0, 0,
    0, 0, 0,
    0, 0,
    0, 0, 0,
    0, 0,
    0, 0, 0,
    0, 0,
    0, 0, 0, 0,
    0, 0, 0,
    120, 1
  )
ON CONFLICT (skill_id) DO UPDATE SET
  skill_code = EXCLUDED.skill_code,
  skill_name = EXCLUDED.skill_name,
  skill_category = EXCLUDED.skill_category,
  skill_type = EXCLUDED.skill_type,
  description = EXCLUDED.description,
  acquire_method = EXCLUDED.acquire_method,
  target_type = EXCLUDED.target_type,
  target_count = EXCLUDED.target_count,
  preferred_target_hp = EXCLUDED.preferred_target_hp,
  animation_key = EXCLUDED.animation_key,
  cast_color = EXCLUDED.cast_color,
  impact_color = EXCLUDED.impact_color,
  projectile = EXCLUDED.projectile,
  is_skill_attack = EXCLUDED.is_skill_attack,
  is_basic_attack = EXCLUDED.is_basic_attack,
  energy_cost = EXCLUDED.energy_cost,
  allow_crit = EXCLUDED.allow_crit,
  ignore_defense = EXCLUDED.ignore_defense,
  attack_pct = EXCLUDED.attack_pct,
  mana_pct = EXCLUDED.mana_pct,
  defense_pct = EXCLUDED.defense_pct,
  speed_pct = EXCLUDED.speed_pct,
  target_current_hp_pct = EXCLUDED.target_current_hp_pct,
  fixed_damage = EXCLUDED.fixed_damage,
  heal_pct = EXCLUDED.heal_pct,
  fixed_heal = EXCLUDED.fixed_heal,
  armor_break_pct = EXCLUDED.armor_break_pct,
  vulnerability_pct = EXCLUDED.vulnerability_pct,
  bleed_chance_pct = EXCLUDED.bleed_chance_pct,
  bleed_rounds = EXCLUDED.bleed_rounds,
  bleed_damage = EXCLUDED.bleed_damage,
  seal_chance_pct = EXCLUDED.seal_chance_pct,
  seal_rounds = EXCLUDED.seal_rounds,
  vulnerability_chance_pct = EXCLUDED.vulnerability_chance_pct,
  vulnerability_rounds = EXCLUDED.vulnerability_rounds,
  vulnerability_apply_pct = EXCLUDED.vulnerability_apply_pct,
  armor_break_chance_pct = EXCLUDED.armor_break_chance_pct,
  armor_break_rounds = EXCLUDED.armor_break_rounds,
  slow_chance_pct = EXCLUDED.slow_chance_pct,
  slow_rounds = EXCLUDED.slow_rounds,
  slow_multiplier_pct = EXCLUDED.slow_multiplier_pct,
  crit_boost_rounds = EXCLUDED.crit_boost_rounds,
  crit_boost_pct = EXCLUDED.crit_boost_pct,
  curse_chance_pct = EXCLUDED.curse_chance_pct,
  curse_rounds = EXCLUDED.curse_rounds,
  curse_damage = EXCLUDED.curse_damage,
  curse_mana_pct = EXCLUDED.curse_mana_pct,
  control_chance_pct = EXCLUDED.control_chance_pct,
  control_rounds = EXCLUDED.control_rounds,
  control_status_id = EXCLUDED.control_status_id,
  sort_weight = EXCLUDED.sort_weight,
  status = EXCLUDED.status,
  updated_at = CURRENT_TIMESTAMP;
