-- 040_player_starter_profile.sql
-- 调整新注册玩家的数据库默认初始属性与背包容量口径。

ALTER TABLE player
  ALTER COLUMN hp SET DEFAULT 148,
  ALTER COLUMN hp_max SET DEFAULT 148,
  ALTER COLUMN energy SET DEFAULT 40,
  ALTER COLUMN energy_max SET DEFAULT 40,
  ALTER COLUMN atk SET DEFAULT 42,
  ALTER COLUMN def SET DEFAULT 15,
  ALTER COLUMN spd SET DEFAULT 11,
  ALTER COLUMN mana SET DEFAULT 30,
  ALTER COLUMN hit_pct SET DEFAULT 95,
  ALTER COLUMN dodge_pct SET DEFAULT 3,
  ALTER COLUMN crit_rate_pct SET DEFAULT 7,
  ALTER COLUMN crit_dmg_pct SET DEFAULT 150,
  ALTER COLUMN base_hp_max SET DEFAULT 148,
  ALTER COLUMN base_atk SET DEFAULT 42,
  ALTER COLUMN base_def SET DEFAULT 15,
  ALTER COLUMN base_spd SET DEFAULT 11,
  ALTER COLUMN base_mana SET DEFAULT 30,
  ALTER COLUMN base_hit_pct SET DEFAULT 95,
  ALTER COLUMN base_dodge_pct SET DEFAULT 3;
