-- 056_seed_pet_skill_slot_items.sql
--
-- 可选开发/测试种子：神符槽解锁道具、法宝镶嵌道具及 pet_skill_slot_unlock_item 映射。
-- 运营环境可按需调整 item_id 与 skill_id，或通过 Admin 维护解锁映射。

INSERT INTO item_definition (
  item_id,
  item_code,
  item_name,
  item_type,
  item_sub_type,
  quality,
  rarity,
  icon,
  "desc",
  max_stack,
  occupy_slots,
  auto_merge,
  sort_weight,
  usable,
  use_scope,
  target_type,
  required_level,
  required_scene_id,
  bind_type,
  can_sell,
  can_drop,
  can_store,
  can_trade,
  expire_at_rule,
  effect_type,
  effect_value,
  effect_params_json,
  buy_price_copper,
  sell_price_copper,
  recycle_price_copper,
  price_type,
  is_enabled
) VALUES
  (
    3010,
    'talisman_slot_1_unlock',
    '神符槽解锁符【1】',
    'consumable',
    'pet_skill_unlock',
    2,
    2,
    '',
    '消耗后为单只宠物开启神符技【1】槽位。',
    99,
    1,
    TRUE,
    230,
    TRUE,
    'world',
    'pet_single',
    1,
    0,
    'none',
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    '',
    'pet_talisman_slot_unlock',
    0,
    '{}'::jsonb,
    1200,
    240,
    0,
    'base_coin',
    TRUE
  ),
  (
    3011,
    'active_talisman_unlock',
    '主动神符解锁符',
    'consumable',
    'pet_skill_unlock',
    3,
    3,
    '',
    '消耗后为单只宠物开启主动神符技槽位。',
    99,
    1,
    TRUE,
    231,
    TRUE,
    'world',
    'pet_single',
    1,
    0,
    'none',
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    '',
    'pet_talisman_slot_unlock',
    0,
    '{}'::jsonb,
    2000,
    400,
    0,
    'base_coin',
    TRUE
  ),
  (
    3020,
    'pet_artifact_spark_stone',
    '法宝·火花灵石',
    'material',
    'pet_artifact',
    2,
    2,
    '',
    '镶嵌后为宠物法宝槽提供技能「火花冲击」。',
    99,
    1,
    TRUE,
    240,
    FALSE,
    'world',
    'pet_single',
    1,
    0,
    'none',
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    '',
    'pet_artifact',
    1002,
    '{"skill_id":1002}'::jsonb,
    1500,
    300,
    0,
    'base_coin',
    TRUE
  ),
  (
    3021,
    'pet_artifact_heal_stone',
    '法宝·治愈之石',
    'material',
    'pet_artifact',
    2,
    2,
    '',
    '镶嵌后为宠物法宝槽提供技能「活力治愈」。',
    99,
    1,
    TRUE,
    241,
    FALSE,
    'world',
    'pet_single',
    1,
    0,
    'none',
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    '',
    'pet_artifact',
    1003,
    '{"skill_id":1003}'::jsonb,
    1500,
    300,
    0,
    'base_coin',
    TRUE
  )
ON CONFLICT (item_id) DO UPDATE SET
  item_code = EXCLUDED.item_code,
  item_name = EXCLUDED.item_name,
  item_type = EXCLUDED.item_type,
  item_sub_type = EXCLUDED.item_sub_type,
  quality = EXCLUDED.quality,
  rarity = EXCLUDED.rarity,
  icon = EXCLUDED.icon,
  "desc" = EXCLUDED."desc",
  max_stack = EXCLUDED.max_stack,
  occupy_slots = EXCLUDED.occupy_slots,
  auto_merge = EXCLUDED.auto_merge,
  sort_weight = EXCLUDED.sort_weight,
  usable = EXCLUDED.usable,
  use_scope = EXCLUDED.use_scope,
  target_type = EXCLUDED.target_type,
  required_level = EXCLUDED.required_level,
  required_scene_id = EXCLUDED.required_scene_id,
  bind_type = EXCLUDED.bind_type,
  can_sell = EXCLUDED.can_sell,
  can_drop = EXCLUDED.can_drop,
  can_store = EXCLUDED.can_store,
  can_trade = EXCLUDED.can_trade,
  expire_at_rule = EXCLUDED.expire_at_rule,
  effect_type = EXCLUDED.effect_type,
  effect_value = EXCLUDED.effect_value,
  effect_params_json = EXCLUDED.effect_params_json,
  buy_price_copper = EXCLUDED.buy_price_copper,
  sell_price_copper = EXCLUDED.sell_price_copper,
  recycle_price_copper = EXCLUDED.recycle_price_copper,
  price_type = EXCLUDED.price_type,
  is_enabled = EXCLUDED.is_enabled,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO pet_skill_slot_unlock_item (slot_key, item_id, description, status)
VALUES
  ('talisman_1', 3010, '神符技【1】槽位解锁道具', 1),
  ('active_talisman', 3011, '主动神符技槽位解锁道具', 1)
ON CONFLICT (slot_key) DO UPDATE SET
  item_id = EXCLUDED.item_id,
  description = EXCLUDED.description,
  status = EXCLUDED.status,
  updated_at = CURRENT_TIMESTAMP;
