-- 075_seed_pet_signature_skills.sql
-- 来源：docs/宠物资料/ 截图（天空之王、苔原守护者等宠物专属圣技/魂技）
-- skill_id 区间 20186-20190；skill_category=pet
-- 复合面板伤害：attack_pct/mana_pct/speed_pct 同时为百分比系数
-- 圣技/魂技 = 必中；ignore_defense=TRUE = 无视防御与抗性真伤（心灵审判）
-- 控制状态 ID：14=圣光忏悔 15=感电 16=混乱之血 12=混乱 13=光之洗礼

INSERT INTO skill_definition (
  skill_id,
  skill_code,
  skill_name,
  skill_category,
  skill_type,
  description,
  acquire_method,
  target_type,
  target_count,
  preferred_target_hp,
  animation_key,
  skill_visual_id,
  cast_color,
  impact_color,
  projectile,
  is_skill_attack,
  is_basic_attack,
  energy_cost,
  allow_crit,
  ignore_defense,
  skill_mult,
  skill_crit_add,
  attack_pct,
  mana_pct,
  defense_pct,
  speed_pct,
  target_current_hp_pct,
  fixed_damage,
  heal_pct,
  fixed_heal,
  armor_break_pct,
  vulnerability_pct,
  bleed_chance_pct,
  bleed_rounds,
  bleed_damage,
  seal_chance_pct,
  seal_power,
  seal_rounds,
  vulnerability_chance_pct,
  vulnerability_rounds,
  vulnerability_apply_pct,
  armor_break_chance_pct,
  armor_break_rounds,
  slow_chance_pct,
  slow_rounds,
  slow_multiplier_pct,
  crit_boost_rounds,
  crit_boost_pct,
  curse_chance_pct,
  curse_rounds,
  curse_damage,
  curse_mana_pct,
  control_chance_pct,
  control_power,
  control_rounds,
  control_status_id,
  sort_weight,
  status
) VALUES
  (
    20186, 'pet_圣技_心灵审判', '圣技·心灵审判', 'pet', 'attack',
    '【全体必中技能】对全体敌人造成（攻击力×400%+法力×2000%+速度×2000%）的真伤，并附加350点混乱威力使敌人混乱2回合（混乱者随机攻击友方，不可叠加）。消耗50点精力。',
    '宠物天生技能', 'enemy_all', 0, '', 'burst', '', '#FFE08A', '#FFF2C8', TRUE, TRUE, FALSE,
    50, FALSE, TRUE, 0, 0, 400, 2000, 0, 2000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 350, 2, 12, 1, 1
  ),
  (
    20187, 'pet_魂技_圣翼之风', '魂技·圣翼之风', 'pet', 'attack',
    '【双体必中技能】随机攻击两名敌人，造成（攻击力×150%+速度×1200%）伤害；75%命中率+325点麻痹威力的圣光忏悔3回合（命中-50、闪避-50、暴伤-200%、物抗/技抗/逆物/逆技各-25，不可叠加）。消耗10点精力。',
    '宠物天生技能', 'enemy_multi', 2, 'random', 'burst', '', '#C6D1FF', '#EBEBF5', TRUE, TRUE, FALSE,
    10, FALSE, FALSE, 0, 0, 150, 0, 0, 1200, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 75, 325, 3, 14, 2, 1
  ),
  (
    20188, 'pet_圣技_光之洗礼', '圣技·光之洗礼', 'pet', 'heal',
    '【单体必中技能】消耗10点精力，回复自身法力×300%的生命，并进入光之洗礼状态4回合：混乱/睡眠/麻痹/封印/诅咒五项不良抗性+200（不可叠加）。',
    '宠物天生技能', 'self', 1, '', 'heal', '', '#FFF7C2', '#FFFFFF', FALSE, TRUE, FALSE,
    10, FALSE, FALSE, 0, 0, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 200, 4, 13, 3, 1
  ),
  (
    20189, 'pet_魂技_雷之咏叹', '魂技·雷之咏叹', 'pet', 'attack',
    '【全体必中技能】对全体敌人造成（攻击力×200%+法力×850%+速度×1500%）伤害；60%命中率+350点麻痹威力的感电3回合（速度-40%、命中-40、闪避-40，不可叠加）。消耗10点精力。',
    '宠物天生技能', 'enemy_all', 0, '', 'burst', '', '#8FD6FF', '#D6F0FF', TRUE, TRUE, FALSE,
    10, FALSE, FALSE, 0, 0, 200, 850, 0, 1500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 60, 350, 3, 15, 4, 1
  ),
  (
    20190, 'pet_魂技_鲜血连斩', '魂技·鲜血连斩', 'pet', 'attack',
    '【双体必中技能】随机攻击两名敌人，造成（速度×800%+法力×800%）伤害；50%命中率+325点混乱威力的混乱之血2回合（混乱者攻击友方，不可叠加）。消耗10点精力。',
    '宠物天生技能', 'enemy_multi', 2, 'random', 'slash', '', '#FF8A8A', '#FFD6D6', FALSE, TRUE, FALSE,
    10, FALSE, FALSE, 0, 0, 0, 800, 0, 800, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 325, 2, 16, 5, 1
  )
ON CONFLICT (skill_id) DO UPDATE SET
  skill_code = EXCLUDED.skill_code,
  skill_name = EXCLUDED.skill_name,
  skill_category = EXCLUDED.skill_category,
  skill_type = EXCLUDED.skill_type,
  description = EXCLUDED.description,
  acquire_method = EXCLUDED.acquire_method,
  target_type = EXCLUDED.target_type,
  target_count = EXCLUDED.target_count,
  preferred_target_hp = EXCLUDED.preferred_target_hp,
  animation_key = EXCLUDED.animation_key,
  skill_visual_id = EXCLUDED.skill_visual_id,
  cast_color = EXCLUDED.cast_color,
  impact_color = EXCLUDED.impact_color,
  projectile = EXCLUDED.projectile,
  is_skill_attack = EXCLUDED.is_skill_attack,
  is_basic_attack = EXCLUDED.is_basic_attack,
  energy_cost = EXCLUDED.energy_cost,
  allow_crit = EXCLUDED.allow_crit,
  ignore_defense = EXCLUDED.ignore_defense,
  skill_mult = EXCLUDED.skill_mult,
  skill_crit_add = EXCLUDED.skill_crit_add,
  attack_pct = EXCLUDED.attack_pct,
  mana_pct = EXCLUDED.mana_pct,
  defense_pct = EXCLUDED.defense_pct,
  speed_pct = EXCLUDED.speed_pct,
  target_current_hp_pct = EXCLUDED.target_current_hp_pct,
  fixed_damage = EXCLUDED.fixed_damage,
  heal_pct = EXCLUDED.heal_pct,
  fixed_heal = EXCLUDED.fixed_heal,
  armor_break_pct = EXCLUDED.armor_break_pct,
  vulnerability_pct = EXCLUDED.vulnerability_pct,
  bleed_chance_pct = EXCLUDED.bleed_chance_pct,
  bleed_rounds = EXCLUDED.bleed_rounds,
  bleed_damage = EXCLUDED.bleed_damage,
  seal_chance_pct = EXCLUDED.seal_chance_pct,
  seal_power = EXCLUDED.seal_power,
  seal_rounds = EXCLUDED.seal_rounds,
  vulnerability_chance_pct = EXCLUDED.vulnerability_chance_pct,
  vulnerability_rounds = EXCLUDED.vulnerability_rounds,
  vulnerability_apply_pct = EXCLUDED.vulnerability_apply_pct,
  armor_break_chance_pct = EXCLUDED.armor_break_chance_pct,
  armor_break_rounds = EXCLUDED.armor_break_rounds,
  slow_chance_pct = EXCLUDED.slow_chance_pct,
  slow_rounds = EXCLUDED.slow_rounds,
  slow_multiplier_pct = EXCLUDED.slow_multiplier_pct,
  crit_boost_rounds = EXCLUDED.crit_boost_rounds,
  crit_boost_pct = EXCLUDED.crit_boost_pct,
  curse_chance_pct = EXCLUDED.curse_chance_pct,
  curse_rounds = EXCLUDED.curse_rounds,
  curse_damage = EXCLUDED.curse_damage,
  curse_mana_pct = EXCLUDED.curse_mana_pct,
  control_chance_pct = EXCLUDED.control_chance_pct,
  control_power = EXCLUDED.control_power,
  control_rounds = EXCLUDED.control_rounds,
  control_status_id = EXCLUDED.control_status_id,
  sort_weight = EXCLUDED.sort_weight,
  status = EXCLUDED.status,
  updated_at = CURRENT_TIMESTAMP;
