-- 076_seed_special_pets_and_signature_skills.sql
-- 三只不可交易特殊圣宠（白色幻影 / 魅惑猫妖 / 恶魔武士）及天生圣技
-- skill_id 20191-20193；pet_id 104-106
-- 控制状态 ID：17=幻影闪击 18=魅惑之风 19=恶魔之力（战斗逻辑见 status_modifier.go）

INSERT INTO skill_definition (
  skill_id,
  skill_code,
  skill_name,
  skill_category,
  skill_type,
  description,
  acquire_method,
  target_type,
  target_count,
  preferred_target_hp,
  animation_key,
  skill_visual_id,
  cast_color,
  impact_color,
  projectile,
  is_skill_attack,
  is_basic_attack,
  energy_cost,
  allow_crit,
  ignore_defense,
  skill_mult,
  skill_crit_add,
  attack_pct,
  mana_pct,
  defense_pct,
  speed_pct,
  target_current_hp_pct,
  fixed_damage,
  heal_pct,
  fixed_heal,
  armor_break_pct,
  vulnerability_pct,
  bleed_chance_pct,
  bleed_rounds,
  bleed_damage,
  seal_chance_pct,
  seal_power,
  seal_rounds,
  vulnerability_chance_pct,
  vulnerability_rounds,
  vulnerability_apply_pct,
  armor_break_chance_pct,
  armor_break_rounds,
  slow_chance_pct,
  slow_rounds,
  slow_multiplier_pct,
  crit_boost_rounds,
  crit_boost_pct,
  curse_chance_pct,
  curse_rounds,
  curse_damage,
  curse_mana_pct,
  control_chance_pct,
  control_power,
  control_rounds,
  control_status_id,
  sort_weight,
  status
) VALUES
  (
    20191, 'pet_圣技_幻影闪击', '圣技·幻影闪击', 'pet', 'attack',
    '【全体必中技能】对全体敌人造成（攻击力×150%+法力×900%+速度×1400%）伤害；75%命中率+325点麻痹威力的幻影闪击3回合（速度-35%、命中-35、闪避-35、暴伤-100%，不可叠加）。消耗10点精力。',
    '宠物天生技能', 'enemy_all', 0, '', 'burst', '', '#E8F4FF', '#FFFFFF', TRUE, TRUE, FALSE,
    10, FALSE, FALSE, 0, 0, 150, 900, 0, 1400, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 75, 325, 3, 17, 6, 1
  ),
  (
    20192, 'pet_圣技_魅惑之风', '圣技·魅惑之风', 'pet', 'attack',
    '【全体必中技能】对全体敌人造成（攻击力×200%+法力×1200%+速度×800%）伤害；75%命中率+325点封印威力的魅惑之风3回合（命中-40、闪避-40、技抗-25、逆技-25，不可叠加）。消耗10点精力。',
    '宠物天生技能', 'enemy_all', 0, '', 'burst', '', '#FFD6F0', '#FFF0FA', TRUE, TRUE, FALSE,
    10, FALSE, FALSE, 0, 0, 200, 1200, 0, 800, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 75, 325, 3, 18, 7, 1
  ),
  (
    20193, 'pet_圣技_恶魔之力', '圣技·恶魔之力', 'pet', 'attack',
    '【全体必中技能】对全体敌人造成（攻击力×700%+法力×500%+速度×300%）伤害；60%命中率+350点诅咒威力的恶魔之力2回合（物抗-30、技抗-30、暴伤-150%，不可叠加）。消耗10点精力。',
    '宠物天生技能', 'enemy_all', 0, '', 'burst', '', '#FFB8B8', '#FFE0E0', TRUE, TRUE, FALSE,
    10, FALSE, FALSE, 0, 0, 700, 500, 0, 300, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 60, 350, 2, 19, 8, 1
  )
ON CONFLICT (skill_id) DO UPDATE SET
  skill_code = EXCLUDED.skill_code,
  skill_name = EXCLUDED.skill_name,
  skill_category = EXCLUDED.skill_category,
  skill_type = EXCLUDED.skill_type,
  description = EXCLUDED.description,
  acquire_method = EXCLUDED.acquire_method,
  target_type = EXCLUDED.target_type,
  target_count = EXCLUDED.target_count,
  preferred_target_hp = EXCLUDED.preferred_target_hp,
  animation_key = EXCLUDED.animation_key,
  skill_visual_id = EXCLUDED.skill_visual_id,
  cast_color = EXCLUDED.cast_color,
  impact_color = EXCLUDED.impact_color,
  projectile = EXCLUDED.projectile,
  is_skill_attack = EXCLUDED.is_skill_attack,
  is_basic_attack = EXCLUDED.is_basic_attack,
  energy_cost = EXCLUDED.energy_cost,
  allow_crit = EXCLUDED.allow_crit,
  ignore_defense = EXCLUDED.ignore_defense,
  skill_mult = EXCLUDED.skill_mult,
  skill_crit_add = EXCLUDED.skill_crit_add,
  attack_pct = EXCLUDED.attack_pct,
  mana_pct = EXCLUDED.mana_pct,
  defense_pct = EXCLUDED.defense_pct,
  speed_pct = EXCLUDED.speed_pct,
  target_current_hp_pct = EXCLUDED.target_current_hp_pct,
  fixed_damage = EXCLUDED.fixed_damage,
  heal_pct = EXCLUDED.heal_pct,
  fixed_heal = EXCLUDED.fixed_heal,
  armor_break_pct = EXCLUDED.armor_break_pct,
  vulnerability_pct = EXCLUDED.vulnerability_pct,
  bleed_chance_pct = EXCLUDED.bleed_chance_pct,
  bleed_rounds = EXCLUDED.bleed_rounds,
  bleed_damage = EXCLUDED.bleed_damage,
  seal_chance_pct = EXCLUDED.seal_chance_pct,
  seal_power = EXCLUDED.seal_power,
  seal_rounds = EXCLUDED.seal_rounds,
  vulnerability_chance_pct = EXCLUDED.vulnerability_chance_pct,
  vulnerability_rounds = EXCLUDED.vulnerability_rounds,
  vulnerability_apply_pct = EXCLUDED.vulnerability_apply_pct,
  armor_break_chance_pct = EXCLUDED.armor_break_chance_pct,
  armor_break_rounds = EXCLUDED.armor_break_rounds,
  slow_chance_pct = EXCLUDED.slow_chance_pct,
  slow_rounds = EXCLUDED.slow_rounds,
  slow_multiplier_pct = EXCLUDED.slow_multiplier_pct,
  crit_boost_rounds = EXCLUDED.crit_boost_rounds,
  crit_boost_pct = EXCLUDED.crit_boost_pct,
  curse_chance_pct = EXCLUDED.curse_chance_pct,
  curse_rounds = EXCLUDED.curse_rounds,
  curse_damage = EXCLUDED.curse_damage,
  curse_mana_pct = EXCLUDED.curse_mana_pct,
  control_chance_pct = EXCLUDED.control_chance_pct,
  control_power = EXCLUDED.control_power,
  control_rounds = EXCLUDED.control_rounds,
  control_status_id = EXCLUDED.control_status_id,
  sort_weight = EXCLUDED.sort_weight,
  status = EXCLUDED.status,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO pet_definition (
  pet_id,
  pet_name,
  description,
  acquire_method,
  status,
  level,
  quality,
  hp,
  hp_max,
  atk,
  def,
  spd,
  mana,
  hp_apt,
  atk_apt,
  def_apt,
  spd_apt,
  mana_apt,
  hp_apt_roll_min,
  hp_apt_roll_max,
  atk_apt_roll_min,
  atk_apt_roll_max,
  def_apt_roll_min,
  def_apt_roll_max,
  spd_apt_roll_min,
  spd_apt_roll_max,
  mana_apt_roll_min,
  mana_apt_roll_max,
  aptitude_profile,
  skin_id,
  innate_skill_ids,
  normal_skill_ids,
  skill_ids
) VALUES
  (
    104,
    '白色幻影',
    '★不可交易★ 特殊圣宠，资质略高于 SS 圣宠，成长空间无限。带出 1 级固定资质。天生 4 宝石孔，可用启魂书开启至 9 孔（法宝槽扩展待后续版本）。加点推荐：生命、速度、法力。宝石推荐：速度、生命、法力、圣品逆抗宝石。技能卡推荐：嗜血、强壮、致命、暴伤。',
    'special_grant_no_trade',
    1,
    1,
    6,
    22,
    22,
    12,
    9,
    8,
    9,
    2658,
    3809,
    2075,
    5269,
    3294,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    'special',
    '白色幻影_001',
    '[20191]'::jsonb,
    '[20053, 20105, 20117]'::jsonb,
    '[20191, 20053, 20105, 20117]'::jsonb
  ),
  (
    105,
    '魅惑猫妖',
    '★不可交易★ 特殊圣宠，资质略高于 SS 圣宠，成长空间无限。带出 1 级固定资质。天生 4 宝石孔，可用启魂书开启至 9 孔（法宝槽扩展待后续版本）。加点推荐：攻击、速度。宝石推荐：法力、速度、圣品逆抗宝石。技能卡推荐：嗜血、致命、暴伤。',
    'special_grant_no_trade',
    1,
    1,
    6,
    22,
    22,
    12,
    9,
    8,
    9,
    3655,
    2943,
    2075,
    2965,
    5446,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    'special',
    '魅惑猫妖_001',
    '[20192]'::jsonb,
    '[20053, 20095, 20105]'::jsonb,
    '[20192, 20053, 20095, 20105]'::jsonb
  ),
  (
    106,
    '恶魔武士',
    '★不可交易★ 特殊圣宠，资质略高于 SS 圣宠，成长空间无限。带出 1 级固定资质。天生 4 宝石孔，可用启魂书开启至 9 孔（法宝槽扩展待后续版本）。加点推荐：攻击、生命。宝石推荐：攻击、生命、圣品逆抗宝石。技能卡推荐：嗜血、致命、暴伤。',
    'special_grant_no_trade',
    1,
    1,
    6,
    22,
    22,
    12,
    9,
    8,
    9,
    3489,
    5888,
    2075,
    2627,
    3464,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    'special',
    '恶魔武士_001',
    '[20193]'::jsonb,
    '[20053, 20105, 20110]'::jsonb,
    '[20193, 20053, 20105, 20110]'::jsonb
  )
ON CONFLICT (pet_id) DO UPDATE SET
  pet_name = EXCLUDED.pet_name,
  description = EXCLUDED.description,
  acquire_method = EXCLUDED.acquire_method,
  status = EXCLUDED.status,
  level = EXCLUDED.level,
  quality = EXCLUDED.quality,
  hp = EXCLUDED.hp,
  hp_max = EXCLUDED.hp_max,
  atk = EXCLUDED.atk,
  def = EXCLUDED.def,
  spd = EXCLUDED.spd,
  mana = EXCLUDED.mana,
  hp_apt = EXCLUDED.hp_apt,
  atk_apt = EXCLUDED.atk_apt,
  def_apt = EXCLUDED.def_apt,
  spd_apt = EXCLUDED.spd_apt,
  mana_apt = EXCLUDED.mana_apt,
  hp_apt_roll_min = EXCLUDED.hp_apt_roll_min,
  hp_apt_roll_max = EXCLUDED.hp_apt_roll_max,
  atk_apt_roll_min = EXCLUDED.atk_apt_roll_min,
  atk_apt_roll_max = EXCLUDED.atk_apt_roll_max,
  def_apt_roll_min = EXCLUDED.def_apt_roll_min,
  def_apt_roll_max = EXCLUDED.def_apt_roll_max,
  spd_apt_roll_min = EXCLUDED.spd_apt_roll_min,
  spd_apt_roll_max = EXCLUDED.spd_apt_roll_max,
  mana_apt_roll_min = EXCLUDED.mana_apt_roll_min,
  mana_apt_roll_max = EXCLUDED.mana_apt_roll_max,
  aptitude_profile = EXCLUDED.aptitude_profile,
  skin_id = EXCLUDED.skin_id,
  innate_skill_ids = EXCLUDED.innate_skill_ids,
  normal_skill_ids = EXCLUDED.normal_skill_ids,
  skill_ids = EXCLUDED.skill_ids,
  updated_at = CURRENT_TIMESTAMP;
