CREATE TABLE IF NOT EXISTS player_combat_snapshot (
    player_id BIGINT PRIMARY KEY REFERENCES player(id) ON DELETE CASCADE,
    hp INTEGER NOT NULL DEFAULT 0,
    hp_max INTEGER NOT NULL DEFAULT 0,
    atk INTEGER NOT NULL DEFAULT 0,
    def INTEGER NOT NULL DEFAULT 0,
    spd INTEGER NOT NULL DEFAULT 0,
    mana INTEGER NOT NULL DEFAULT 0,
    vigor INTEGER NOT NULL DEFAULT 0,
    vigor_max INTEGER NOT NULL DEFAULT 0,
    spirit INTEGER NOT NULL DEFAULT 0,
    spirit_max INTEGER NOT NULL DEFAULT 0,
    hit_pct INTEGER NOT NULL DEFAULT 0,
    dodge_pct INTEGER NOT NULL DEFAULT 0,
    crit_rate_pct INTEGER NOT NULL DEFAULT 0,
    crit_dmg_pct INTEGER NOT NULL DEFAULT 0,
    physical_resist_pct INTEGER NOT NULL DEFAULT 0,
    skill_resist_pct INTEGER NOT NULL DEFAULT 0,
    confusion_resist_pct INTEGER NOT NULL DEFAULT 0,
    sleep_resist_pct INTEGER NOT NULL DEFAULT 0,
    paralysis_resist_pct INTEGER NOT NULL DEFAULT 0,
    seal_resist_pct INTEGER NOT NULL DEFAULT 0,
    curse_resist_pct INTEGER NOT NULL DEFAULT 0,
    crit_resist_pct INTEGER NOT NULL DEFAULT 0,
    crit_dmg_resist_pct INTEGER NOT NULL DEFAULT 0,
    character_resist_pct INTEGER NOT NULL DEFAULT 0,
    pet_resist_pct INTEGER NOT NULL DEFAULT 0,
    mercenary_resist_pct INTEGER NOT NULL DEFAULT 0,
    generic_shield_pct INTEGER NOT NULL DEFAULT 0,
    guard INTEGER NOT NULL DEFAULT 0,
    talent_dmg_pct INTEGER NOT NULL DEFAULT 0,
    talent_reduce_pct INTEGER NOT NULL DEFAULT 0,
    element_adv_pct INTEGER NOT NULL DEFAULT 0,
    element_penalty_pct INTEGER NOT NULL DEFAULT 0,
    skill_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    skin_id TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS player_pet_combat_snapshot (
    pet_uid BIGINT PRIMARY KEY REFERENCES player_pet(id) ON DELETE CASCADE,
    player_id BIGINT NOT NULL REFERENCES player(id) ON DELETE CASCADE,
    pet_id INTEGER NOT NULL DEFAULT 0,
    level INTEGER NOT NULL DEFAULT 1,
    exp BIGINT NOT NULL DEFAULT 0,
    quality INTEGER NOT NULL DEFAULT 1,
    hp INTEGER NOT NULL DEFAULT 0,
    hp_max INTEGER NOT NULL DEFAULT 0,
    atk INTEGER NOT NULL DEFAULT 0,
    def INTEGER NOT NULL DEFAULT 0,
    spd INTEGER NOT NULL DEFAULT 0,
    mana INTEGER NOT NULL DEFAULT 0,
    spirit INTEGER NOT NULL DEFAULT 0,
    spirit_max INTEGER NOT NULL DEFAULT 0,
    hit_pct INTEGER NOT NULL DEFAULT 0,
    dodge_pct INTEGER NOT NULL DEFAULT 0,
    crit_rate_pct INTEGER NOT NULL DEFAULT 0,
    crit_dmg_pct INTEGER NOT NULL DEFAULT 0,
    physical_resist_pct INTEGER NOT NULL DEFAULT 0,
    reverse_physical_resist_pct INTEGER NOT NULL DEFAULT 0,
    skill_resist_pct INTEGER NOT NULL DEFAULT 0,
    reverse_skill_resist_pct INTEGER NOT NULL DEFAULT 0,
    confusion_resist_pct INTEGER NOT NULL DEFAULT 0,
    sleep_resist_pct INTEGER NOT NULL DEFAULT 0,
    paralysis_resist_pct INTEGER NOT NULL DEFAULT 0,
    seal_resist_pct INTEGER NOT NULL DEFAULT 0,
    curse_resist_pct INTEGER NOT NULL DEFAULT 0,
    crit_dmg_resist_pct INTEGER NOT NULL DEFAULT 0,
    crit_resist_pct INTEGER NOT NULL DEFAULT 0,
    character_resist_pct INTEGER NOT NULL DEFAULT 0,
    pet_resist_pct INTEGER NOT NULL DEFAULT 0,
    guard INTEGER NOT NULL DEFAULT 0,
    talent_dmg_pct INTEGER NOT NULL DEFAULT 0,
    talent_reduce_pct INTEGER NOT NULL DEFAULT 0,
    element_adv_pct INTEGER NOT NULL DEFAULT 0,
    element_penalty_pct INTEGER NOT NULL DEFAULT 0,
    skill_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    innate_skill_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    normal_skill_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    grant_source TEXT NOT NULL DEFAULT '',
    capture_monster_id INTEGER NOT NULL DEFAULT 0,
    free_attr_points INTEGER NOT NULL DEFAULT 0,
    alloc_hp_points INTEGER NOT NULL DEFAULT 0,
    alloc_atk_points INTEGER NOT NULL DEFAULT 0,
    alloc_spd_points INTEGER NOT NULL DEFAULT 0,
    alloc_mana_points INTEGER NOT NULL DEFAULT 0,
    alloc_def_points INTEGER NOT NULL DEFAULT 0,
    base_hp_apt INTEGER NOT NULL DEFAULT 0,
    base_atk_apt INTEGER NOT NULL DEFAULT 0,
    base_def_apt INTEGER NOT NULL DEFAULT 0,
    base_spd_apt INTEGER NOT NULL DEFAULT 0,
    base_mana_apt INTEGER NOT NULL DEFAULT 0,
    extra_hp_apt INTEGER NOT NULL DEFAULT 0,
    extra_atk_apt INTEGER NOT NULL DEFAULT 0,
    extra_def_apt INTEGER NOT NULL DEFAULT 0,
    extra_spd_apt INTEGER NOT NULL DEFAULT 0,
    extra_mana_apt INTEGER NOT NULL DEFAULT 0,
    evolution_level INTEGER NOT NULL DEFAULT 0,
    rebirth_level INTEGER NOT NULL DEFAULT 0,
    aptitude_profile TEXT NOT NULL DEFAULT 'normal',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_player_pet_combat_snapshot_player_id
    ON player_pet_combat_snapshot (player_id);
