-- 修正宠物公共技能描述中“模板描述 + 后缀真实数值”导致的前半段错误，并为关键数值补充 BBCode 富文本。
-- 数据来源：docs/pocket_pet_public_skill_definition.csv 中后缀数值，例如“2.45倍伤害/24%概率失手”。
UPDATE skill_definition AS sd
SET
  description = v.description,
  updated_at = now()
FROM (
  VALUES
    ('寒蝉F', '该法力技能按法力×[color=green]2.2[/color]攻击敌人，同时有[color=#e6b422]140[/color]点封印威力使敌人处于寒蝉状态，无法使用技能。每次使用该技能消耗[color=red]24[/color]点精力；该技能额外附加[color=green]8[/color]点命中。'),
    ('厚甲神技', '【被动技】提升[color=green]20[/color]点物理抗性。'),
    ('厚甲A', '【被动技】提升[color=green]15[/color]点物理抗性。'),
    ('厚甲C', '【被动技】提升[color=green]8[/color]点物理抗性。'),
    ('厚甲D', '【被动技】提升[color=green]6[/color]点物理抗性。'),
    ('厚甲E', '【被动技】提升[color=green]5[/color]点物理抗性。'),
    ('厚甲F', '【被动技】提升[color=green]4[/color]点物理抗性。'),
    ('寒蝉D', '该法力技能按法力×[color=green]2.6[/color]攻击敌人，同时有[color=#e6b422]140[/color]点封印威力使敌人处于寒蝉状态，无法使用技能。每次使用该技能消耗[color=red]20[/color]点精力；该技能额外附加[color=green]24[/color]点命中。'),
    ('寒蝉E', '该法力技能按法力×[color=green]2.4[/color]攻击敌人，同时有[color=#e6b422]140[/color]点封印威力使敌人处于寒蝉状态，无法使用技能。每次使用该技能消耗[color=red]22[/color]点精力；该技能额外附加[color=green]16[/color]点命中。'),
    ('电流C', '最强单体法力技能，每 [color=#e6b422]1[/color] 点法力会获得[color=green]5.3[/color]点技能伤害。每次使用该技能需要消耗[color=red]12[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('电流D', '最强单体法力技能，每 [color=#e6b422]1[/color] 点法力会获得[color=green]4.7[/color]点技能伤害。每次使用该技能需要消耗[color=red]14[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('电流E', '最强单体法力技能，每 [color=#e6b422]1[/color] 点法力会获得[color=green]4.1[/color]点技能伤害。每次使用该技能需要消耗[color=red]16[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('电流F', '最强单体法力技能，每 [color=#e6b422]1[/color] 点法力会获得[color=green]3.5[/color]点技能伤害。每次使用该技能需要消耗[color=red]17[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('审判神技', '打出 [color=green]3.2[/color] 倍的普通攻击力伤害，但有[color=red]16[/color]%的概率失手，失手后会帮助敌人回复生命。每次使用该技能需要消耗[color=red]11[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('审判A', '打出 [color=green]2.9[/color] 倍的普通攻击力伤害，但有[color=red]20[/color]%的概率失手，失手后会帮助敌人回复生命。每次使用该技能需要消耗[color=red]11[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('审判C', '打出 [color=green]2.45[/color] 倍的普通攻击力伤害，但有[color=red]24[/color]%的概率失手，失手后会帮助敌人回复生命。每次使用该技能需要消耗[color=red]11[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('审判D', '打出 [color=green]2.3[/color] 倍的普通攻击力伤害，但有[color=red]25[/color]%的概率失手，失手后会帮助敌人回复生命。每次使用该技能需要消耗[color=red]11[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('审判E', '打出 [color=green]2.15[/color] 倍的普通攻击力伤害，但有[color=red]26[/color]%的概率失手，失手后会帮助敌人回复生命。每次使用该技能需要消耗[color=red]11[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('审判F', '打出 [color=green]2[/color] 倍的普通攻击力伤害，但有[color=red]27[/color]%的概率失手，失手后会帮助敌人回复生命。每次使用该技能需要消耗[color=red]11[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('噬魂神技', '造成[color=green]80[/color]%物理攻击力伤害敌人，同时减少敌人[color=#e6b422]26[/color]点精力。每次使用该技能需要消耗[color=red]10[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('噬魂A', '造成[color=green]60[/color]%物理攻击力伤害敌人，同时减少敌人[color=#e6b422]22[/color]点精力。每次使用该技能需要消耗[color=red]10[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('噬魂C', '造成[color=green]30[/color]%物理攻击力伤害敌人，同时减少敌人[color=#e6b422]16[/color]点精力。每次使用该技能需要消耗[color=red]10[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('噬魂D', '造成[color=green]20[/color]%物理攻击力伤害敌人，同时减少敌人[color=#e6b422]14[/color]点精力。每次使用该技能需要消耗[color=red]10[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('噬魂E', '造成[color=green]10[/color]%物理攻击力伤害敌人，同时减少敌人[color=#e6b422]12[/color]点精力。每次使用该技能需要消耗[color=red]10[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('噬魂F', '造成[color=green]100[/color]%物理攻击力伤害敌人，同时减少敌人[color=#e6b422]10[/color]点精力。每次使用该技能需要消耗[color=red]10[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('魂技.嗜血', '【被动技】拥有此技能时，将对敌人造成伤害的[color=green]50[/color]%转化为自己的气血，作用在多人的时候效果会减弱。'),
    ('温泉神技', '同时恢复全体队友的生命，恢复量为法力值×[color=green]10[/color]。每次使用该技能需要消耗[color=red]10[/color]点精力。'),
    ('温泉A', '同时恢复全体队友的生命，恢复量为法力值×[color=green]8.5[/color]。每次使用该技能需要消耗[color=red]16[/color]点精力。'),
    ('温泉C', '同时恢复全体队友的生命，恢复量为法力值×[color=green]6.2[/color]。每次使用该技能需要消耗[color=red]25[/color]点精力。'),
    ('温泉D', '同时恢复全体队友的生命，恢复量为法力值×[color=green]5.6[/color]。每次使用该技能需要消耗[color=red]28[/color]点精力。'),
    ('暴伤C', '【被动技】提升[color=green]60[/color]点暴伤。'),
    ('温泉E', '同时恢复全体队友的生命，恢复量为法力值×[color=green]4.8[/color]。每次使用该技能需要消耗[color=red]31[/color]点精力。'),
    ('温泉F', '同时恢复全体队友的生命，恢复量为法力值×[color=green]4[/color]。每次使用该技能需要消耗[color=red]34[/color]点精力。'),
    ('霞光神技', '当前回合提升 [color=green]300[/color] 点速度释放此法力技能，力求抢先攻击敌人。每 [color=#e6b422]1[/color] 点法力会获得[color=green]4.8[/color]点技能伤害。每次使用该技能需要消耗[color=red]11[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('霞光A', '当前回合提升 [color=green]225[/color] 点速度释放此法力技能，力求抢先攻击敌人。每 [color=#e6b422]1[/color] 点法力会获得[color=green]4.5[/color]点技能伤害。每次使用该技能需要消耗[color=red]11[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('霞光C', '当前回合提升 [color=green]125[/color] 点速度释放此法力技能，力求抢先攻击敌人。每 [color=#e6b422]1[/color] 点法力会获得[color=green]3.9[/color]点技能伤害。每次使用该技能需要消耗[color=red]11[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('霞光D', '当前回合提升 [color=green]100[/color] 点速度释放此法力技能，力求抢先攻击敌人。每 [color=#e6b422]1[/color] 点法力会获得[color=green]3.6[/color]点技能伤害。每次使用该技能需要消耗[color=red]11[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('霞光E', '当前回合提升 [color=green]75[/color] 点速度释放此法力技能，力求抢先攻击敌人。每 [color=#e6b422]1[/color] 点法力会获得[color=green]3.3[/color]点技能伤害。每次使用该技能需要消耗[color=red]11[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('霞光F', '当前回合提升 [color=green]50[/color] 点速度释放此法力技能，力求抢先攻击敌人。每 [color=#e6b422]1[/color] 点法力会获得[color=green]3[/color]点技能伤害。每次使用该技能需要消耗[color=red]11[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('飓风神技', '伤害全体的法力技能，每 [color=#e6b422]1[/color] 点法力会获得[color=green]4.8[/color]点技能伤害，但是命中率比普通攻击降低[color=red]20[/color]点。每次使用该技能需要消耗[color=red]12[/color]点精力；使用该技能的命中额外附加[color=green]20[/color]点。'),
    ('飓风A', '伤害全体的法力技能，每 [color=#e6b422]1[/color] 点法力会获得[color=green]4.2[/color]点技能伤害，但是命中率比普通攻击降低[color=red]20[/color]点。每次使用该技能需要消耗[color=red]18[/color]点精力；使用该技能的命中额外附加[color=green]20[/color]点。'),
    ('飓风C', '伤害全体的法力技能，每 [color=#e6b422]1[/color] 点法力会获得[color=green]3.3[/color]点技能伤害，但是命中率比普通攻击降低[color=red]20[/color]点。每次使用该技能需要消耗[color=red]25[/color]点精力；使用该技能的命中额外附加[color=green]20[/color]点。'),
    ('飓风D', '伤害全体的法力技能，每 [color=#e6b422]1[/color] 点法力会获得[color=green]3[/color]点技能伤害，但是命中率比普通攻击降低[color=red]20[/color]点。每次使用该技能需要消耗[color=red]28[/color]点精力；使用该技能的命中额外附加[color=green]20[/color]点。'),
    ('飓风E', '伤害全体的法力技能，每 [color=#e6b422]1[/color] 点法力会获得[color=green]2.7[/color]点技能伤害，但是命中率比普通攻击降低[color=red]20[/color]点。每次使用该技能需要消耗[color=red]31[/color]点精力；使用该技能的命中额外附加[color=green]20[/color]点。'),
    ('飓风F', '伤害全体的法力技能，每 [color=#e6b422]1[/color] 点法力会获得[color=green]2.4[/color]点技能伤害，但是命中率比普通攻击降低[color=red]20[/color]点。每次使用该技能需要消耗[color=red]34[/color]点精力；使用该技能的命中额外附加[color=green]20[/color]点。'),
    ('冷血神技', '使用后，恢复 [color=green]1000[/color] 点生命，并提升对所有劣性状态的抵抗度 [color=green]100[/color] 点。每次使用该技能需要消耗[color=red]12[/color]点精力。'),
    ('冷血A', '使用后，恢复 [color=green]750[/color] 点生命，并提升对所有劣性状态的抵抗度 [color=green]80[/color] 点。每次使用该技能需要消耗[color=red]12[/color]点精力。'),
    ('冷血C', '使用后，恢复 [color=green]400[/color] 点生命，并提升对所有劣性状态的抵抗度 [color=green]50[/color] 点。每次使用该技能需要消耗[color=red]12[/color]点精力。'),
    ('冷血D', '使用后，恢复 [color=green]300[/color] 点生命，并提升对所有劣性状态的抵抗度 [color=green]40[/color] 点。每次使用该技能需要消耗[color=red]12[/color]点精力。'),
    ('冷血E', '使用后，恢复 [color=green]200[/color] 点生命，并提升对所有劣性状态的抵抗度 [color=green]30[/color] 点。每次使用该技能需要消耗[color=red]12[/color]点精力。'),
    ('冷血F', '使用后，恢复 [color=green]100[/color] 点生命，并提升对所有劣性状态的抵抗度 [color=green]20[/color] 点。每次使用该技能需要消耗[color=red]12[/color]点精力。'),
    ('暴走神技', '提升[color=green]1.6[/color]倍的物理攻击力和[color=green]50[/color]点致命一击与命中属性攻击敌人，但会不辨敌我，随机攻击任何一个战斗单体。'),
    ('暴走A', '提升[color=green]1.4[/color]倍的物理攻击力和[color=green]46[/color]点致命一击与命中属性攻击敌人，但会不辨敌我，随机攻击任何一个战斗单体。'),
    ('暴走C', '提升[color=green]1.1[/color]倍的物理攻击力和[color=green]40[/color]点致命一击与命中属性攻击敌人，但会不辨敌我，随机攻击任何一个战斗单体。'),
    ('暴走D', '提升[color=green]1[/color]倍的物理攻击力和[color=green]38[/color]点致命一击与命中属性攻击敌人，但会不辨敌我，随机攻击任何一个战斗单体。'),
    ('暴走E', '提升[color=green]0.9[/color]倍的物理攻击力和[color=green]36[/color]点致命一击与命中属性攻击敌人，但会不辨敌我，随机攻击任何一个战斗单体。'),
    ('爱吻神技', '大幅恢复单个队友的生命，恢复量为法力值×[color=green]11.5[/color]。每次使用该技能需要消耗[color=red]5[/color]点精力。'),
    ('爱吻A', '大幅恢复单个队友的生命，恢复量为法力值×[color=green]10[/color]。每次使用该技能需要消耗[color=red]8[/color]点精力。'),
    ('爱吻C', '大幅恢复单个队友的生命，恢复量为法力值×[color=green]7.7[/color]。每次使用该技能需要消耗[color=red]12[/color]点精力。'),
    ('爱吻D', '大幅恢复单个队友的生命，恢复量为法力值×[color=green]7.1[/color]。每次使用该技能需要消耗[color=red]14[/color]点精力。'),
    ('爱吻E', '大幅恢复单个队友的生命，恢复量为法力值×[color=green]6.3[/color]。每次使用该技能需要消耗[color=red]16[/color]点精力。'),
    ('爱吻F', '大幅恢复单个队友的生命，恢复量为法力值×[color=green]5.5[/color]。每次使用该技能需要消耗[color=red]17[/color]点精力。'),
    ('暴走F', '提升[color=green]0.8[/color]倍的物理攻击力和[color=green]34[/color]点致命一击与命中属性攻击敌人，但会不辨敌我，随机攻击任何一个战斗单体。'),
    ('暴伤D', '【被动技】提升[color=green]50[/color]点暴伤。'),
    ('冰华神技', '同时伤害[color=#e6b422]2[/color]个目标的法力技能。每 [color=#e6b422]1[/color] 点法力会获得[color=green]7[/color]点技能伤害。每次使用该技能需要消耗[color=red]8[/color]点精力；使用该技能的命中额外附加[color=green]30[/color]点。'),
    ('冰华A', '同时伤害[color=#e6b422]2[/color]个目标的法力技能。每 [color=#e6b422]1[/color] 点法力会获得[color=green]6[/color]点技能伤害。每次使用该技能需要消耗[color=red]12[/color]点精力；使用该技能的命中额外附加[color=green]30[/color]点。'),
    ('冰华C', '同时伤害[color=#e6b422]2[/color]个目标的法力技能。每 [color=#e6b422]1[/color] 点法力会获得[color=green]4.4[/color]点技能伤害。每次使用该技能需要消耗[color=red]18[/color]点精力；使用该技能的命中额外附加[color=green]30[/color]点。'),
    ('冰华D', '同时伤害[color=#e6b422]2[/color]个目标的法力技能。每 [color=#e6b422]1[/color] 点法力会获得[color=green]4[/color]点技能伤害。每次使用该技能需要消耗[color=red]20[/color]点精力；使用该技能的命中额外附加[color=green]30[/color]点。'),
    ('冰华E', '同时伤害[color=#e6b422]2[/color]个目标的法力技能。每 [color=#e6b422]1[/color] 点法力会获得[color=green]3.65[/color]点技能伤害。每次使用该技能需要消耗[color=red]22[/color]点精力；使用该技能的命中额外附加[color=green]30[/color]点。'),
    ('冰华F', '同时伤害[color=#e6b422]2[/color]个目标的法力技能。每 [color=#e6b422]1[/color] 点法力会获得[color=green]3.3[/color]点技能伤害。每次使用该技能需要消耗[color=red]24[/color]点精力；使用该技能的命中额外附加[color=green]30[/color]点。'),
    ('寒蝉神技', '该法力技能按法力×[color=green]5[/color]攻击敌人，同时有[color=#e6b422]140[/color]点封印威力使敌人处于寒蝉状态，无法使用技能。每次使用该技能消耗[color=red]8[/color]点精力；该技能额外附加[color=green]80[/color]点命中。'),
    ('毒焰神技', '强劲的单体法力技能。每 [color=#e6b422]1[/color] 点法力会获得[color=green]6[/color]点技能伤害，一定概率使敌人中[color=#e6b422]3[/color]回合的中毒吐血，每回合伤害敌人[color=red]1100[/color]点气血。每次使用该技能需要消耗[color=red]11[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('毒焰A', '强劲的单体法力技能。每 [color=#e6b422]1[/color] 点法力会获得[color=green]5.2[/color]点技能伤害，一定概率使敌人中[color=#e6b422]3[/color]回合的中毒吐血，每回合伤害敌人[color=red]800[/color]点气血。每次使用该技能需要消耗[color=red]11[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('毒焰C', '强劲的单体法力技能。每 [color=#e6b422]1[/color] 点法力会获得[color=green]4.1[/color]点技能伤害，一定概率使敌人中[color=#e6b422]3[/color]回合的中毒吐血，每回合伤害敌人[color=red]400[/color]点气血。每次使用该技能需要消耗[color=red]11[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('毒焰D', '强劲的单体法力技能。每 [color=#e6b422]1[/color] 点法力会获得[color=green]3.8[/color]点技能伤害，一定概率使敌人中[color=#e6b422]3[/color]回合的中毒吐血，每回合伤害敌人[color=red]300[/color]点气血。每次使用该技能需要消耗[color=red]11[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('魂技.反噬', '【被动技】受到攻击时，有[color=green]80[/color]%的概率用普通攻击反击敌人。'),
    ('寒蝉A', '该法力技能按法力×[color=green]4[/color]攻击敌人，同时有[color=#e6b422]140[/color]点封印威力使敌人处于寒蝉状态，无法使用技能。每次使用该技能消耗[color=red]12[/color]点精力；该技能额外附加[color=green]60[/color]点命中。'),
    ('毒焰E', '强劲的单体法力技能。每 [color=#e6b422]1[/color] 点法力会获得[color=green]3.5[/color]点技能伤害，一定概率使敌人中[color=#e6b422]3[/color]回合的中毒吐血，每回合伤害敌人[color=red]200[/color]点气血。每次使用该技能需要消耗[color=red]11[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('毒焰F', '强劲的单体法力技能。每 [color=#e6b422]1[/color] 点法力会获得[color=green]3.2[/color]点技能伤害，一定概率使敌人中[color=#e6b422]3[/color]回合的中毒吐血，每回合伤害敌人[color=red]100[/color]点气血。每次使用该技能需要消耗[color=red]11[/color]点精力；使用该技能的命中额外附加[color=green]40[/color]点。'),
    ('嗜血神技', '【被动技】拥有此技能时，将对敌人造成伤害的[color=green]30[/color]%转化为自己的气血，作用在多人的时候效果会减弱。'),
    ('嗜血A', '【被动技】拥有此技能时，将对敌人造成伤害的[color=green]23[/color]%转化为自己的气血，作用在多人的时候效果会减弱。'),
    ('嗜血C', '【被动技】拥有此技能时，将对敌人造成伤害的[color=green]12[/color]%转化为自己的气血，作用在多人的时候效果会减弱。'),
    ('嗜血D', '【被动技】拥有此技能时，将对敌人造成伤害的[color=green]10[/color]%转化为自己的气血，作用在多人的时候效果会减弱。'),
    ('致命A', '【被动技】拥有此技能将提升[color=green]20[/color]点致命一击的属性。'),
    ('暴伤F', '【被动技】提升[color=green]30[/color]点暴伤。'),
    ('嗜血E', '【被动技】拥有此技能时，将对敌人造成伤害的[color=green]8[/color]%转化为自己的气血，作用在多人的时候效果会减弱。'),
    ('嗜血F', '【被动技】拥有此技能时，将对敌人造成伤害的[color=green]6[/color]%转化为自己的气血，作用在多人的时候效果会减弱。'),
    ('致命C', '【被动技】拥有此技能将提升[color=green]10[/color]点致命一击的属性。'),
    ('致命D', '【被动技】拥有此技能将提升[color=green]8[/color]点致命一击的属性。'),
    ('致命E', '【被动技】拥有此技能将提升[color=green]6[/color]点致命一击的属性。'),
    ('致命F', '【被动技】拥有此技能将提升[color=green]5[/color]点致命一击的属性。'),
    ('坚韧神技', '【被动技】提升[color=green]30[/color]点所有不良状态的抗性。'),
    ('坚韧A', '【被动技】提升[color=green]25[/color]点所有不良状态的抗性。'),
    ('坚韧C', '【被动技】提升[color=green]12[/color]点所有不良状态的抗性。'),
    ('坚韧D', '【被动技】提升[color=green]10[/color]点所有不良状态的抗性。'),
    ('坚韧E', '【被动技】提升[color=green]8[/color]点所有不良状态的抗性。'),
    ('坚韧F', '【被动技】提升[color=green]6[/color]点所有不良状态的抗性。'),
    ('结界神技', '【被动技】提升[color=green]20[/color]点技能抗性。'),
    ('结界A', '【被动技】提升[color=green]15[/color]点技能抗性。'),
    ('结界C', '【被动技】提升[color=green]8[/color]点技能抗性。'),
    ('结界D', '【被动技】提升[color=green]6[/color]点技能抗性。'),
    ('结界E', '【被动技】提升[color=green]5[/color]点技能抗性。'),
    ('结界F', '【被动技】提升[color=green]4[/color]点技能抗性。'),
    ('连击神技', '【被动技】每次攻击敌人时，有[color=green]30[/color]%的概率额外追加一次普通物理攻击。'),
    ('连击A', '【被动技】每次攻击敌人时，有[color=green]25[/color]%的概率额外追加一次普通物理攻击。'),
    ('连击C', '【被动技】每次攻击敌人时，有[color=green]12[/color]%的概率额外追加一次普通物理攻击。'),
    ('连击D', '【被动技】每次攻击敌人时，有[color=green]10[/color]%的概率额外追加一次普通物理攻击。'),
    ('连击E', '【被动技】每次攻击敌人时，有[color=green]8[/color]%的概率额外追加一次普通物理攻击。'),
    ('连击F', '【被动技】每次攻击敌人时，有[color=green]6[/color]%的概率额外追加一次普通物理攻击。'),
    ('魔心神技', '【被动技】拥有此技能的宠物会提升[color=green]30[/color]%的法力属性。'),
    ('魔心A', '【被动技】拥有此技能的宠物会提升[color=green]25[/color]%的法力属性。'),
    ('魔心C', '【被动技】拥有此技能的宠物会提升[color=green]12[/color]%的法力属性。'),
    ('魔心D', '【被动技】拥有此技能的宠物会提升[color=green]10[/color]%的法力属性。'),
    ('魔心E', '【被动技】拥有此技能的宠物会提升[color=green]8[/color]%的法力属性。'),
    ('魔心F', '【被动技】拥有此技能的宠物会提升[color=green]6[/color]%的法力属性。'),
    ('涅槃F', '【被动技】当被敌人杀死时，有[color=green]6[/color]%的概率生命全满复活！'),
    ('涅槃E', '【被动技】当被敌人杀死时，有[color=green]8[/color]%的概率生命全满复活！'),
    ('涅槃D', '【被动技】当被敌人杀死时，有[color=green]10[/color]%的概率生命全满复活！'),
    ('涅槃C', '【被动技】当被敌人杀死时，有[color=green]12[/color]%的概率生命全满复活！'),
    ('涅槃A', '【被动技】当被敌人杀死时，有[color=green]25[/color]%的概率生命全满复活！'),
    ('涅槃神技', '【被动技】当被敌人杀死时，有[color=green]30[/color]%的概率生命全满复活！'),
    ('涅槃魂技', '【被动技】当被敌人杀死时，有[color=green]50[/color]%的概率生命全满复活！'),
    ('强力神技', '【被动技】拥有此技能的宠物将提升[color=green]30[/color]%的攻击力。'),
    ('强力A', '【被动技】拥有此技能的宠物将提升[color=green]25[/color]%的攻击力。'),
    ('强力C', '【被动技】拥有此技能的宠物将提升[color=green]12[/color]%的攻击力。'),
    ('强力D', '【被动技】拥有此技能的宠物将提升[color=green]10[/color]%的攻击力。'),
    ('强力E', '【被动技】拥有此技能的宠物将提升[color=green]8[/color]%的攻击力。'),
    ('强力F', '【被动技】拥有此技能的宠物将提升[color=green]6[/color]%的攻击力。'),
    ('迅捷神技', '【被动技】拥有此技能的宠物将提升[color=green]20[/color]%的速度属性。'),
    ('迅捷A', '【被动技】拥有此技能的宠物将提升[color=green]15[/color]%的速度属性。'),
    ('迅捷C', '【被动技】拥有此技能的宠物将提升[color=green]8[/color]%的速度属性。'),
    ('迅捷D', '【被动技】拥有此技能的宠物将提升[color=green]6[/color]%的速度属性。'),
    ('迅捷E', '【被动技】拥有此技能的宠物将提升[color=green]5[/color]%的速度属性。'),
    ('迅捷F', '【被动技】拥有此技能的宠物将提升[color=green]4[/color]%的速度属性。'),
    ('暴伤神技', '【被动技】提升[color=green]150[/color]点暴伤。'),
    ('暴伤A', '【被动技】提升[color=green]110[/color]点暴伤。'),
    ('暴伤E', '【被动技】提升[color=green]40[/color]点暴伤。'),
    ('刺甲神技', '【被动技】每次受到敌人攻击时，将伤害数值的[color=green]20[/color]%反弹给敌人，反弹伤害的时候无视敌人的抗性和防御。'),
    ('刺甲A', '【被动技】每次受到敌人攻击时，将伤害数值的[color=green]15[/color]%反弹给敌人，反弹伤害的时候无视敌人的抗性和防御。'),
    ('刺甲C', '【被动技】每次受到敌人攻击时，将伤害数值的[color=green]8[/color]%反弹给敌人，反弹伤害的时候无视敌人的抗性和防御。'),
    ('刺甲D', '【被动技】每次受到敌人攻击时，将伤害数值的[color=green]6[/color]%反弹给敌人，反弹伤害的时候无视敌人的抗性和防御。'),
    ('刺甲E', '【被动技】每次受到敌人攻击时，将伤害数值的[color=green]5[/color]%反弹给敌人，反弹伤害的时候无视敌人的抗性和防御。'),
    ('刺甲F', '【被动技】每次受到敌人攻击时，将伤害数值的[color=green]4[/color]%反弹给敌人，反弹伤害的时候无视敌人的抗性和防御。'),
    ('反噬神技', '【被动技】受到攻击时，有[color=green]50[/color]%的概率用普通攻击反击敌人。'),
    ('反噬A', '【被动技】受到攻击时，有[color=green]35[/color]%的概率用普通攻击反击敌人。'),
    ('反噬C', '【被动技】受到攻击时，有[color=green]12[/color]%的概率用普通攻击反击敌人。'),
    ('反噬D', '【被动技】受到攻击时，有[color=green]10[/color]%的概率用普通攻击反击敌人。'),
    ('反噬E', '【被动技】受到攻击时，有[color=green]8[/color]%的概率用普通攻击反击敌人。'),
    ('反噬F', '【被动技】受到攻击时，有[color=green]6[/color]%的概率用普通攻击反击敌人。')
) AS v(skill_name, description)
WHERE sd.skill_category = 'pet'
  AND sd.skill_name = v.skill_name;
