-- 093_seed_missing_pet_b_skills_from_xlsx.sql
-- 来源：docs/宠物技能详解.（风车.熊主）.xlsx 的「无垢者之城NPC(B,C)」页。
-- 目的：补齐早期荫凉之地技能迁移未覆盖的 B 品级宠物技能，并直接写入富文本描述。
-- 注意：当前 skill_definition 字段暂时无法表达「施法者自晕」「伤害超过阈值才触发控制」
--       和「中毒时无法补血」这类特殊规则；本迁移先写入现有战斗引擎可结算的伤害、
--       控制、易伤/中毒字段，后续如补齐专用结算逻辑可继续用迁移修正字段。

INSERT INTO skill_definition (
  skill_id,
  skill_code,
  skill_name,
  skill_category,
  skill_type,
  description,
  acquire_method,
  target_type,
  target_count,
  preferred_target_hp,
  animation_key,
  skill_visual_id,
  cast_color,
  impact_color,
  projectile,
  is_skill_attack,
  is_basic_attack,
  energy_cost,
  allow_crit,
  ignore_defense,
  skill_mult,
  skill_crit_add,
  attack_pct,
  mana_pct,
  defense_pct,
  speed_pct,
  target_current_hp_pct,
  fixed_damage,
  heal_pct,
  fixed_heal,
  armor_break_pct,
  vulnerability_pct,
  bleed_chance_pct,
  bleed_rounds,
  bleed_damage,
  seal_chance_pct,
  seal_power,
  seal_rounds,
  vulnerability_chance_pct,
  vulnerability_rounds,
  vulnerability_apply_pct,
  armor_break_chance_pct,
  armor_break_rounds,
  slow_chance_pct,
  slow_rounds,
  slow_multiplier_pct,
  crit_boost_rounds,
  crit_boost_pct,
  curse_chance_pct,
  curse_rounds,
  curse_damage,
  curse_mana_pct,
  control_chance_pct,
  control_power,
  control_rounds,
  control_status_id,
  activation_mode,
  passive_attr_key,
  passive_attr_mode,
  passive_attr_value,
  sort_weight,
  status
) VALUES
  (
    20194, 'pet_全力冲撞B', '全力冲撞B', 'pet', 'attack',
    '宠物主动技能，以[color=green]270%[/color]攻击力冲撞敌人，之后自己会晕厥[color=#e6b422]2[/color]回合；如果伤害超过[color=green]10000[/color]，敌人也有少许可能被晕厥。',
    '无垢者之城宠物技能卡（6000积分）', 'enemy_single', 1, '', 'slash', '', '#FFB36B', '#FFE0B8', FALSE,
    TRUE, FALSE, 0, TRUE, FALSE,
    27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 2, 3,
    'active', '', '', 0, 194, 1
  ),
  (
    20195, 'pet_灵心术B', '灵心术B', 'pet', 'support',
    '【被动技】使用技能时节约精力。',
    '无垢者之城宠物技能卡（8500积分）', 'self', 0, '', 'passive', '', '#EBEBF5', '#FFF2F2', FALSE,
    FALSE, FALSE, 0, TRUE, FALSE,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    'passive', '', '', 0, 195, 1
  ),
  (
    20196, 'pet_梦魇B', '梦魇B', 'pet', 'attack',
    '宠物主动技能，以攻击力与法力造成双攻伤害，并附加[color=#e6b422]125[/color]点睡眠威力，使敌人睡眠[color=#e6b422]3[/color]回合并降低[color=red]35%[/color]防御。',
    '无垢者之城宠物技能卡（11000积分）', 'enemy_single', 1, '', 'burst', '', '#8F7CFF', '#E1D8FF', TRUE,
    TRUE, FALSE, 0, TRUE, FALSE,
    0, 0, 100, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 3, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 125, 3, 10,
    'active', '', '', 0, 196, 1
  ),
  (
    20197, 'pet_毒焰旋风B', '毒焰旋风B', 'pet', 'attack',
    '宠物主动技能，对全体敌人施加[color=#e6b422]200[/color]点诅咒威力，使敌人中[color=#e6b422]5[/color]回合毒；中毒时每回合损失宠物法力×[color=green]60%[/color]的生命，且无法补血。',
    '无垢者之城宠物技能卡（18000积分）', 'enemy_all', 0, '', 'burst', '', '#73F5A3', '#FFE0E0', TRUE,
    TRUE, FALSE, 0, FALSE, FALSE,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 5, 0, 60, 0, 0, 0, 0,
    'active', '', '', 0, 197, 1
  )
ON CONFLICT (skill_id) DO UPDATE SET
  skill_code = EXCLUDED.skill_code,
  skill_name = EXCLUDED.skill_name,
  skill_category = EXCLUDED.skill_category,
  skill_type = EXCLUDED.skill_type,
  description = EXCLUDED.description,
  acquire_method = EXCLUDED.acquire_method,
  target_type = EXCLUDED.target_type,
  target_count = EXCLUDED.target_count,
  preferred_target_hp = EXCLUDED.preferred_target_hp,
  animation_key = EXCLUDED.animation_key,
  skill_visual_id = EXCLUDED.skill_visual_id,
  cast_color = EXCLUDED.cast_color,
  impact_color = EXCLUDED.impact_color,
  projectile = EXCLUDED.projectile,
  is_skill_attack = EXCLUDED.is_skill_attack,
  is_basic_attack = EXCLUDED.is_basic_attack,
  energy_cost = EXCLUDED.energy_cost,
  allow_crit = EXCLUDED.allow_crit,
  ignore_defense = EXCLUDED.ignore_defense,
  skill_mult = EXCLUDED.skill_mult,
  skill_crit_add = EXCLUDED.skill_crit_add,
  attack_pct = EXCLUDED.attack_pct,
  mana_pct = EXCLUDED.mana_pct,
  defense_pct = EXCLUDED.defense_pct,
  speed_pct = EXCLUDED.speed_pct,
  target_current_hp_pct = EXCLUDED.target_current_hp_pct,
  fixed_damage = EXCLUDED.fixed_damage,
  heal_pct = EXCLUDED.heal_pct,
  fixed_heal = EXCLUDED.fixed_heal,
  armor_break_pct = EXCLUDED.armor_break_pct,
  vulnerability_pct = EXCLUDED.vulnerability_pct,
  bleed_chance_pct = EXCLUDED.bleed_chance_pct,
  bleed_rounds = EXCLUDED.bleed_rounds,
  bleed_damage = EXCLUDED.bleed_damage,
  seal_chance_pct = EXCLUDED.seal_chance_pct,
  seal_power = EXCLUDED.seal_power,
  seal_rounds = EXCLUDED.seal_rounds,
  vulnerability_chance_pct = EXCLUDED.vulnerability_chance_pct,
  vulnerability_rounds = EXCLUDED.vulnerability_rounds,
  vulnerability_apply_pct = EXCLUDED.vulnerability_apply_pct,
  armor_break_chance_pct = EXCLUDED.armor_break_chance_pct,
  armor_break_rounds = EXCLUDED.armor_break_rounds,
  slow_chance_pct = EXCLUDED.slow_chance_pct,
  slow_rounds = EXCLUDED.slow_rounds,
  slow_multiplier_pct = EXCLUDED.slow_multiplier_pct,
  crit_boost_rounds = EXCLUDED.crit_boost_rounds,
  crit_boost_pct = EXCLUDED.crit_boost_pct,
  curse_chance_pct = EXCLUDED.curse_chance_pct,
  curse_rounds = EXCLUDED.curse_rounds,
  curse_damage = EXCLUDED.curse_damage,
  curse_mana_pct = EXCLUDED.curse_mana_pct,
  control_chance_pct = EXCLUDED.control_chance_pct,
  control_power = EXCLUDED.control_power,
  control_rounds = EXCLUDED.control_rounds,
  control_status_id = EXCLUDED.control_status_id,
  activation_mode = EXCLUDED.activation_mode,
  passive_attr_key = EXCLUDED.passive_attr_key,
  passive_attr_mode = EXCLUDED.passive_attr_mode,
  passive_attr_value = EXCLUDED.passive_attr_value,
  sort_weight = EXCLUDED.sort_weight,
  status = EXCLUDED.status,
  updated_at = CURRENT_TIMESTAMP;
